# Competição Perfeita e Monopólio

## Introdução

Neste capítulo, iremos recapitular duas estruturas de mercado mais comumente apresentadas em cursos de Microeconomia: (i) Competição Perfeita e (ii) Monopólio. No caso da competição perfeita, podemos apresentá-la como um padrão de comparação sobre as estruturas de mercado que vêm depois, e no caso de Monopólio podemos ressaltar alguns aspectos importantes de mercados em competição perfeita -- o papel da entrada e o papel de eventuais competidores (a chamada Franja Competitiva).


## Competição e Competição Perfeita

Nesta seção do capítulo, iremos revisitar o conceito de Competição e Competição Perfeita. Digo revisitar porque, novamente, estou assumindo que o leitor deste livro já tenha estudado este tema algumas vezes. 
Então, aqui os objetivos principais vão ser:

* Deixar claro o que se entende por um *mercado competitivo*
* Deixar claro o que se entende por um *mercado perfeitamente competitivo*

Esta distinção é importante porque o mercado perfeitamente competitivo vai ser entendido ao longo deste livro como sendo o padrão de comparação contra o qual as outras estruturas de mercado. Além disso, ao fazer a distinção entre um mercado competitivo e um mercado competitivo, podemos também iluminar o seguinte ponto: ainda que um mercado perfeitamente competitivo seja um ideal e dificilmente encontrável no mundo real, mercados no mundo real podem aproximar os resultados do mercado perfeitamente competitivo -- ou seja, há benefícios em observar as conclusões do modelo de competição perfeita como uma forma de entender a realidade também, se entendermos que é uma aproximação ao mundo real.

Vamos então com a definição mais tradicional, que é a do livro do Carlton e Perloff. Competição Perfeita é definida como uma estrutura de mercado com as seguintes características:
* Bens homogêneos: aos olhos dos consumidores todos os ofertantes são idênticos, e aos olhos dos ofertantes todos os consumidores são idênticos. Note-se que o aspecto aqui importante está na frase ``nos olhos'' -- você não necessariamente precisa que os produtos sejam fisicamente idênticos.
* Comportamento tomador de preços: Isso significa que nenhum dos ofertantes (e nenhum dos demandantes) é capaz de afetar os preços de mercado por meio das suas compras/vendas.
* Não existem custos de transação: Os compradores não incorrem em custos (entendidos como custos econômicos) quando da realização de suas compras - e o mesmo valendo pros consumidores
* Não temos externalidades reais: As decisões de compra e venda não afetam outras pessoas por mecanismos que não sejam os de mercado.
* Livre Entrada: Os ofertantes e demandantes podem entrar no mercado se assim desejarem (=acharem lucrativo)
* Divisibilidade: as quantidades produzidas podem ser infinitamente divisíveis

Como mencionado mais acima, estas premissas caracterizam um tipo de mercado que dificilmente pode ser encontrado no ``mundo real''. A partir dessa informação, existem duas reações. A primeira delas é entender que o papel desta definição é justamente este -- ser restritiva para fornecer um padrão de comparação para os modelos que nós detalharemos mais adiante. 

A segunda reação é pensar se, dado que estas condições caracterizam um mercado dificilmente encontrado no mundo real, existe um subconjunto destas condições que seria mais próxima do mundo real e que gere resultados parecidos com o de competição perfeita. Se entendermos ``resultados parecidos'' como sendo preços convergindo para um equilíbrio - que chamarei de *mercado competitivo* como o resultado da interação de curvas de oferta e de demanda, o que a evidência experimental [@smith1962experimental] e [@FriedmanOstroy1995] nos mostra é que apenas as seguintes premissas são necessárias:

* Os compradores conhecem as suas disposições a pagar
* Os vendedores conhecem o custo marginal de oportunidade das unidades que estão dispostas a oferecer
* Os compradores e vendedores conhecem o preço de mercado

Note-se que isso não significa que seja possível que outros aspectos (informação, custos de transação) sejam de tal magnitude que impeça que o resultado de mercado competitivo se estabeleça. E nem que todas as consequências de um mercado em competição perfeita também se verifique.

E por falar no equilíbrio em competição perfeita, na seção seguinte iremos reapresentar o mesmo.

### Equilíbrio em Competição Perfeita


## Monopólio

Nesta nota, iremos detalhar um pouco a ideia do monopólio, e expressar algumas relações que vocês já conhecem em outros contextos em uma forma que enfatiza a generalidade com o que vem depois. Inicialmente vamos falar o monopólio tradicional, para depois falarmos da questão da firma dominante com a franja competitiva.

### Monopólio -- Versão tradicional

Vamos supor que o monopólio enfrente uma curva de demanda do tipo $P(Q)$ e possua uma função de Custo total da forma $CT(Q)$. O lucro do monopolista, desta forma, fica sendo:

$$
\begin{aligned}
\pi_{m}=Q\times P(Q)-CT(Q)
\end{aligned}
$$

Derivando e igualando a zero, temos então o seguinte:

$$
\begin{aligned}
\frac{\partial \pi}{\partial Q} = P - \frac{\partial CT}{\partial Q} + Q \frac{\partial P}{\partial Q} = 0\\
\frac{P-\frac{\partial CT}{\partial Q}}{P}= - \frac{Q}{P}\frac{\partial P}{\partial Q}\\
\frac{P-\frac{\partial CT}{\partial Q}}{P} = \frac{1}{|\varepsilon_{D}|}
\end{aligned}
$$

O lado esquerdo desta igualdade é o chamado ``Índice de Lerner'', uma medida percentual da margem preço-custo marginal (em base percentual). O lado direito é o inverso da elasticidade-preço da demanda. Essa equação é bastante intuitiva, no sentido que mercados com demandas mais elásticas permitem menos elevação dos preços acima dos custos marginais.

Uma forma alternativa de escrever esta última equação é:

$$
P=\frac{\frac{\partial CT}{\partial Q}}{1-\frac{1}{|\varepsilon_{D}|}}
$$

### Firma Dominante -- Franja Competitiva

Não há muita diferença na ideia de Firma Dominante com Franja Competitiva. O único ponto diferente é que a firma dominante trabalha com a Demanda Residual, definida de forma similar à do capítulo anterior do Carlton e Perloff: $D_{R}(P)=D(P)-S_{0}(P)$. Vamos apresentar a solução ótima por meio da escolha de preços:

$$
\begin{aligned}
\pi_{m}=P \times D_{R}(P) - CT(D_{R}(P))\\
\frac{\partial \pi_{m}}{\partial P} = D_{R} + P \frac{\partial D_{R}}{\partial P} - \frac{\partial CT}{\partial Q} \frac{\partial D_{R}}{\partial P}=0\\
P \frac{\partial D_{R}}{\partial P} - \frac{\partial CT}{\partial Q} \frac{\partial D_{R}}{\partial P}=-D_{R}\\
P-\frac{\partial CT}{\partial Q}=\frac{1}{\frac{\partial D_{R}}{\partial P}} D_{R}\\
\left( \frac{P-\frac{\partial CT}{\partial Q}}{P} \right)=\frac{1}{|\varepsilon_{D_{R}}|}
\end{aligned}
$$
A única diferença neste caso é a inclinação da demanda residual -- $D_{R}$ ao invés de $D$. Em alguns casos é possível que a inclinação coincida (quando a franja está ativa), em outros não coincide.
