---
title: "Oligopólio de Cournot"
author: "Claudio Lucinda"
date: "21 de março de 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introdução

Nesta nota, iremos trabalhar um dos principais modelos para entender competição imperfeita, o Modelo de Cournot. Inicialmente iremos fazer uma demonstração mais geral, para depois especializarmos para uma demanda linear.

### Resultado geral

Vamos assumir que existam $n$ empresas neste mercado, cada uma indexada por $i$. A decisão delas é sobre o quanto produzir, representada por $q_{i}$. O custo marginal de produção é constante e não necessariamente idêntico entre as empresas. 
O preço de mercado é igual para todas as empresas e é o resultado da quantidade **total** produzida, $P=f(\sum_{i=1}^{n} q_{i})=f(Q)$, de acordo com o que se espera de uma função demanda, $f^{\prime}<0$. Com essa definição, temos a seguinte expressão para a função receita marginal:

$$
\begin{aligned}
RT_{i}&=P\times q_{i}\\
RMg_{i}&=\frac{\partial RT_{i}}{\partial q_{i}}=P+q_{i}\times \frac{\partial P}{\partial Q}\times \sum_{j=1}^{n}\frac{\partial q_{j}}{\partial q_{i}}
\end{aligned}
$$

A expressão para a receita marginal neste caso pode ser expressa informalmente da seguinte forma. O efeito de um aumento marginal na quantidade produzida é o preço destas unidades marginais produzidas menos o efeito desta quantidade marginal produzida sobre os preços de mercado. A diferença desta expressão em relação à de monopólio é que o efeito final sobre a quantidade total depende do aumento da própria empresa $i$ e de o que a empresa $i$ considera que seus oponentes $j\neq i$ farão em resposta à ação de $i$ -- daí esses componentes da somatória serem também conhecidos como ``variações conjecturais''.

Estas variações conjecturais são conhecidas desde os anos 60 do século passado; todavia, apenas com a formalização em teoria dos jogos que se conseguiu mapear de forma mais organizada o que se entende ou se espera destas variações conjecturais. Basicamente, aqui iremos utilizar o conceito de equilíbrio de Nash para a determinação do equilíbrio -- o que faz com que esta função receita marginal seja base para a construção das Funções Melhor Resposta. 

Basicamente, a melhor resposta para uma firma $i$ vai ser a escolha de quantidades para esta empresa que maximiza seus lucros assumindo que as quantidades dos seus oponentes sejam constantes. 

Com esta premissa, temos:

$$
\begin{aligned}
\frac{\partial q_{j}}{\partial q_{i}}&=0,j\neq i\\
\frac{\partial q_{j}}{\partial q_{i}}&=1,j= i\\
\end{aligned}
$$

Com isso, a função melhor resposta fica sendo:

$$
\begin{aligned}
RMg_{i}-CMg_{i}&=0\\
P-CMg_{i}+q_{i}\times \frac{\partial P}{\partial Q}&=0\\
\frac{P-CMg_{i}}{P}&=\frac{q_{i}}{Q}\times \frac{1}{|\varepsilon_{D}|}=\frac{s_{i}}{|\varepsilon_{D}|}
\end{aligned}
$$

Supondo que esta condição valha para cada uma das empresas, temos que as margens preço-lucro aqui são iguais à razão entre a participação de mercado e o valor absoluto da elasticidade-preço da demanda. Intuitivamente, empresas mais eficientes (com menores custos marginais) tem maiores margens preço-custo marginal e maiores participações de mercado.

Outro resultado interessante acontece quando tentamos calcular a margem preço-custo média da indústria:

$$
\begin{aligned}
\sum_{i=1}^{n}s_{i} \times \frac{P-CMg_{i}}{P}&=\sum_{i=1}^{n}\frac{s_{i}^{2}}{|\varepsilon_{D}|}\\
\frac{P-\overline{CMg_{i}}}{P}&=\frac{HHI}{|\varepsilon_{D}|}
\end{aligned}
$$
Em que $HHI$ é o chamado Índice Herfindahl-Hirschman. Se as premissas do modelo de Cournot forem válidas (competição por quantidades, produtos homogêneos), uma forma de avaliar a competitividade em um mercado sem ter que descobrir quais seriam os custos marginais é simplesmente calcular o Índice Herfindahl-Hirschman.

### Exemplo: Demanda Linear

Vamos agora assumir uma demanda e custos marginais lineares, e duas empresas. A vantagem dessa abordagem é que ela permite que apresentamos as coisas de forma gráfica. Como anteriormente, vamos assumir que a demanda inversa é uma função das quantidades produzidas das duas empresas

$$
P=a-b(q_{1}+q_{2})
$$
Como disse anteriormente, os custos marginais são constantes, o que significa que $CT_{i}=c_{i}\times q_{i}, i=1,2$.

As funções lucro das empresas 1 e 2 são da seguinte forma então:

$$
\begin{aligned}
\pi_{i}&=(P-c_{i})q_{i}=(a-b(q_{1}+q_{2})-c_{i})q_{i}\\
\pi_{1}&=(P-c_{1})q_{1}=(a-b(q_{1}+q_{2})-c_{1})q_{1}\\
\pi_{2}&=(P-c_{2})q_{2}=(a-b(q_{1}+q_{2})-c_{2})q_{2}
\end{aligned}
$$

Podemos construir duas coisas a partir das funções lucro $\pi_{i}$: as funções isolucro e as funções melhor resposta. A primeira delas é o lugar geométrico dos pontos correspondentes a um determinado nível de lucro, e a segunda diz, para uma determinada quantidade de uma das empresas, quanto o seu oponente deveria produzir para maximizar seus lucros.

Esta última podemos derivar a partir das condições de primeira ordem:

$$
\frac{\partial \pi_{1}}{\partial q_{1}}=(a-2bq_{1}-bq_{2}-c_{1})=0
$$

Reorganizando, chegamos às seguintes funções melhor resposta:

$$
\begin{aligned}
q_{1}&=\frac{a-bq_{2}-c_{1}}{2b}\\
q_{2}&=\frac{a-bq_{1}-c_{2}}{2b}
\end{aligned}
$$

O equilíbrio de Nash deste jogo acontece quando temos as duas funções melhor resposta valendo simultaneamente. Ou seja, quando resolvemos o sistema de duas equações em duas incógnitas. Supondo custos marginais constantes, temos as seguintes quantidades e preço de equilíbrio:

$$
\begin{aligned}
q_{1}=q_{2}&=\frac{a-c}{3b}\\
Q&=2\frac{a-c}{3b}\\
P&=\frac{a+2c}{3}
\end{aligned}
$$

Podemos ver graficamente esta solução a partir da figura a seguir:

<iframe scrolling='no' frameborder='0' src='https://www.wolframcloud.com/objects/demonstrations/CournotCompetitionWithTwoFirms?_view=EMBED' style='border:0;' width= '600' height='650'></iframe>

Primeira coisa interessante deste modelo de Cournot é que ele consegue representar um ``caminho intermediário'' entre o monopólio e competição perfeita. Por exemplo, em um mercado monopolizado, teríamos o seguinte:

$$
\begin{aligned}
Q&=\frac{a-c}{2b}\\
P&=\frac{a+c}{2}
\end{aligned}
$$

Esta seria a quantidade de equilíbrio que um cartel que buscasse maximizar os lucros também produziria. Supondo firmas idênticas, teríamos $q_{i}=\frac{a-c}{4b}$. O problema é que esta configuração não é um equilíbrio estável. Se as duas empresas estiverem produzindo isso, a melhor resposta de uma delas é aumentar um pouco sua produção.

O segundo ponto interessante é que o modelo de Cournot mantém essa característica de ``caso intermediário'' à medida em que variamos o número de empresas.

### Modelo de Cournot com muitas firmas

Usando a mesma forma de demanda e custos, apenas assumindo que as firmas são idênticas e que ao invés de duas, existem $n$ empresas. A função demanda fica sendo então:

$$
P=a-b(\sum_{j=1}^{n}q_{j})
$$

A função lucro de uma firma específica fica então sendo:

$$
\pi_{i}=(a-b(\sum_{j=1}^{n}q_{j})-c)q_{i}
$$

Vamos ter as seguintes Condições de Primeira Ordem:

$$
\frac{\pi_{i}}{q_{i}}=a-b(\sum_{j=1}^{n}q_{j})-bq_{i}-c=0
$$

Reorganizando, chegamos à seguinte função melhor resposta para a empresa genérica $i$:

$$
q_{i}=\frac{a-b\sum_{j=1}^{n}q_{j}-c}{b}
$$

Se as empresas são iguais, espera-se que elas em equilíbrio produzam a mesma coisa, ou seja, $q_{i}=q_{j}=q^{*}$

$$
\begin{aligned}
q^{*}&=\frac{a-bnq^{*}-c}{b}\\
q^{*}&=\frac{1}{n+1}\frac{a-c}{b}\\
Q=nq^{*}&=\frac{n}{n+1}\frac{a-c}{b}\\
P=&\frac{a}{n+1}+c\frac{n}{n+1}
\end{aligned}
$$

Com $n\rightarrow \infty$, temos que a solução se aproxima de competição perfeita. 