---
title: "Oligopólio de Stackelberg"
author: "Claudio Lucinda"
date: "21 de março de 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introdução

No modelo de Cournot que vimos anteriormente, consideramos o jogo simultâneo, ou seja, não havia possibilidade de um dos jogadores agir de forma condicional ao que o outro fizesse. Em muitos casos isso não é verdade. Vamos supor, ainda usando a estrutura do modelo de Cournot da aula passada, que uma das empresas é capaz de agir de forma condicional ao que o seu oponente fizesse. Este modelo foi desenvolvido em 1934 por Heinrich von Stackelberg e por isso é chamado, não surpreendentemente, de ``Modelo de Stackelberg'', ou modelo da firma líder e firma seguidora.

### Apresentação do modelo

Vamos supor que existam duas firmas em um mercado, representadas por $i=1,2$. No entanto, neste mercado a primeira das companhias também tem precedência na escolha da quantidade produzida em relação à segunda. Ou, em outras palavras, a segunda empresa pode reagir ao que a primeira fizer. Este fato pode ser devido a um monte de motivos, seja por uma tecnologia mais avançada ou admiistração mais eficiente. 

Como são as estratégias destas empresas? A da firma 1 -- que vou chamar de líder -- é bastante simples, a determinação de um valor para a quantidade produzida. 
Já para a firma 2 a definição de estratégias é mais complexa, pois especifica uma ação para a firma 2 para cada quantidade produzida pela firma 1. 

Veremos como isto é operacionalizado usando a mesma premissa de demanda linear e custos marginais constantes que vimos anteriormente, ou:


$$
P=a-b(q_{1}+q_{2})
$$

Vamos assumir também que os custos marginais são constantes e iguais, o que significa que $CT_{i}=c\times q_{i}, i=1,2$. Isso leva às seguintes funções lucro para cada uma das firmas.


$$
\begin{aligned}
\pi_{i}&=(P-c_{i})q_{i}=(a-b(q_{1}+q_{2})-c)q_{i}\\
\pi_{1}&=(P-c_{1})q_{1}=(a-b(q_{1}+q_{2})-c)q_{1}\\
\pi_{2}&=(P-c_{2})q_{2}=(a-b(q_{1}+q_{2})-c)q_{2}
\end{aligned}
$$

Aí aqui começa a aparecer a diferença entre este modelo. Uma vez que o jogo é sequencial, temos que resolver este jogo por indução retrospectiva. Para a firma 2, a seguidora que se move depois, temos uma função melhor resposta tradicional -- ela toma como dada a quantidade produzida pela empresa 1 e escolhe qual a quantidade que, para ela, maximiza seus lucros.

$$
\begin{aligned}
\frac{\partial \pi_{2}}{\partial q_{2}}&=a-2bq_{2}-bq_{1}-cq_{2}\\
q_{2}&=\frac{a-bq_{1}-c}{2b}
\end{aligned}
$$

Esta função melhor resposta da firma 2 será utilizada para derivarmos o equilíbrio na primeira etapa. Como? Por meio da substituição desta função melhor resposta na função lucro da firma 1. Ou seja, temos:

$$
\begin{aligned}
\pi_{1}&=\left(a-b\left( \frac{2bq_{1}+a -bq_{1}-c}{2b} \right)  \right)q_{q}-cq_{1}\\
\pi_{1}&=\left(a-\frac{1}{2}\left(a + bq_{1}-c \right)  \right)q_{q}-cq_{1}
\end{aligned}
$$

Derivando esta função lucro em termos da estratégia a ser escolhida pela empresa 1, temos então:

$$
\begin{aligned}
\frac{\partial \pi_{1}}{\partial q_{1}} &= \frac{a-c}{2}-bq_{1}=0\\
q_{1}&=\frac{a-c}{2b}
\end{aligned}
$$

Podemos agora obter a quantidade produzida pela empresa 2, simplesmente substituindo o último dos resultados na função melhor resposta mais acima.

$$
\begin{aligned}
q_{2}&=\frac{a-c-b\left(\frac{a-c}{2b} \right)}{2b}\\
q_{2}&=\frac{a-c}{4b}
\end{aligned}
$$

Podemos notar que este modelo implica que a empresa que pode reagir acaba tendo menor produção e menores lucros que a empresa que não reage. Este é um tipo de situação em que não há vantagem em se ter flexibilidade; muito pelo contrário, há vantagens para o comprometimento.