<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capitulo 4 Interdependencia Estrategica | Organização Industrial</title>
  <meta name="description" content="Livro de Organização Industrial." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Capitulo 4 Interdependencia Estrategica | Organização Industrial" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Livro de Organização Industrial." />
  <meta name="github-repo" content="openscapes/series" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capitulo 4 Interdependencia Estrategica | Organização Industrial" />
  
  <meta name="twitter:description" content="Livro de Organização Industrial." />
  

<meta name="author" content="Claudio Ribeiro de Lucinda" />


<meta name="date" content="2021-05-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="competição-perfeita-e-monopólio.html"/>
<link rel="next" href="modelo-de-mankiw-e-whinston.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="lib/css/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="lib/css/style.css" type="text/css" />
<link rel="stylesheet" href="lib/css/lesson.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Livro Organização Industrial</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Apresentação</a></li>
<li class="chapter" data-level="2" data-path="funções-custo.html"><a href="funções-custo.html"><i class="fa fa-check"></i><b>2</b> Funções Custo</a>
<ul>
<li class="chapter" data-level="2.1" data-path="funções-custo.html"><a href="funções-custo.html#introdução"><i class="fa fa-check"></i><b>2.1</b> Introdução</a></li>
<li class="chapter" data-level="2.2" data-path="funções-custo.html"><a href="funções-custo.html#funções-de-produção-e-de-custo-conhecidas"><i class="fa fa-check"></i><b>2.2</b> Funções de Produção e de Custo conhecidas</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="funções-custo.html"><a href="funções-custo.html#cobb-douglas"><i class="fa fa-check"></i><b>2.2.1</b> Cobb-Douglas</a></li>
<li class="chapter" data-level="2.2.2" data-path="funções-custo.html"><a href="funções-custo.html#ces"><i class="fa fa-check"></i><b>2.2.2</b> CES</a></li>
<li class="chapter" data-level="2.2.3" data-path="funções-custo.html"><a href="funções-custo.html#leontief"><i class="fa fa-check"></i><b>2.2.3</b> Leontief</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="funções-custo.html"><a href="funções-custo.html#medidas-de-economias-de-escala-e-economias-de-escopo"><i class="fa fa-check"></i><b>2.3</b> Medidas de Economias de Escala e Economias de Escopo</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="funções-custo.html"><a href="funções-custo.html#empresas-multiproduto"><i class="fa fa-check"></i><b>2.3.1</b> Empresas Multiproduto</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="funções-custo.html"><a href="funções-custo.html#funções-de-custo-empíricas"><i class="fa fa-check"></i><b>2.4</b> Funções de Custo Empíricas</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="competição-perfeita-e-monopólio.html"><a href="competição-perfeita-e-monopólio.html"><i class="fa fa-check"></i><b>3</b> Competição Perfeita e Monopólio</a>
<ul>
<li class="chapter" data-level="3.1" data-path="competição-perfeita-e-monopólio.html"><a href="competição-perfeita-e-monopólio.html#introdução-1"><i class="fa fa-check"></i><b>3.1</b> Introdução</a></li>
<li class="chapter" data-level="3.2" data-path="competição-perfeita-e-monopólio.html"><a href="competição-perfeita-e-monopólio.html#competição-e-competição-perfeita"><i class="fa fa-check"></i><b>3.2</b> Competição e Competição Perfeita</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="competição-perfeita-e-monopólio.html"><a href="competição-perfeita-e-monopólio.html#equilíbrio-em-competição-perfeita"><i class="fa fa-check"></i><b>3.2.1</b> Equilíbrio em Competição Perfeita</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="competição-perfeita-e-monopólio.html"><a href="competição-perfeita-e-monopólio.html#monopólio"><i class="fa fa-check"></i><b>3.3</b> Monopólio</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="competição-perfeita-e-monopólio.html"><a href="competição-perfeita-e-monopólio.html#monopólio-versão-tradicional"><i class="fa fa-check"></i><b>3.3.1</b> Monopólio – Versão tradicional</a></li>
<li class="chapter" data-level="3.3.2" data-path="competição-perfeita-e-monopólio.html"><a href="competição-perfeita-e-monopólio.html#monopsônio"><i class="fa fa-check"></i><b>3.3.2</b> Monopsônio</a></li>
<li class="chapter" data-level="3.3.3" data-path="competição-perfeita-e-monopólio.html"><a href="competição-perfeita-e-monopólio.html#firma-dominante-franja-competitiva"><i class="fa fa-check"></i><b>3.3.3</b> Firma Dominante – Franja Competitiva</a></li>
<li class="chapter" data-level="3.3.4" data-path="competição-perfeita-e-monopólio.html"><a href="competição-perfeita-e-monopólio.html#econometria-estimando-a-demanda-residual-por-eletricidade"><i class="fa fa-check"></i><b>3.3.4</b> Econometria: Estimando a Demanda Residual por Eletricidade</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html"><i class="fa fa-check"></i><b>4</b> Interdependencia Estrategica</a>
<ul>
<li class="chapter" data-level="4.1" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#cartel"><i class="fa fa-check"></i><b>4.1</b> Cartel</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#história-o-cartel-dos-geradores-de-eletricidade"><i class="fa fa-check"></i><b>4.1.1</b> História – o cartel dos geradores de eletricidade</a></li>
<li class="chapter" data-level="4.1.2" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#teoria-jogos-repetidos"><i class="fa fa-check"></i><b>4.1.2</b> Teoria: Jogos Repetidos</a></li>
<li class="chapter" data-level="4.1.3" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#brasil-legislação-contra-carteis"><i class="fa fa-check"></i><b>4.1.3</b> Brasil: Legislação Contra Carteis</a></li>
<li class="chapter" data-level="4.1.4" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#exercício-empírico-o-joint-executive-committee"><i class="fa fa-check"></i><b>4.1.4</b> Exercício Empírico – o <em>Joint Executive Committee</em></a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#oligopólio"><i class="fa fa-check"></i><b>4.2</b> Oligopólio</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#resultado-geral"><i class="fa fa-check"></i><b>4.2.1</b> Resultado geral</a></li>
<li class="chapter" data-level="4.2.2" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#exemplo-demanda-linear"><i class="fa fa-check"></i><b>4.2.2</b> Exemplo: Demanda Linear</a></li>
<li class="chapter" data-level="4.2.3" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#modelo-de-cournot-com-muitas-firmas"><i class="fa fa-check"></i><b>4.2.3</b> Modelo de Cournot com muitas firmas</a></li>
<li class="chapter" data-level="4.2.4" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#exposição-inicial"><i class="fa fa-check"></i><b>4.2.4</b> Exposição Inicial</a></li>
<li class="chapter" data-level="4.2.5" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#bertrand-com-produtos-diferenciados"><i class="fa fa-check"></i><b>4.2.5</b> Bertrand com Produtos Diferenciados</a></li>
<li class="chapter" data-level="4.2.6" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#jogos-sequenciais-em-bertrand"><i class="fa fa-check"></i><b>4.2.6</b> Jogos sequenciais em Bertrand</a></li>
<li class="chapter" data-level="4.2.7" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#bertrand-multiproduto"><i class="fa fa-check"></i><b>4.2.7</b> Bertrand Multiproduto</a></li>
<li class="chapter" data-level="4.2.8" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#bertrand-com-restrições-de-capacidade"><i class="fa fa-check"></i><b>4.2.8</b> Bertrand com restrições de capacidade</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#modelos-sequenciais-stackelberg"><i class="fa fa-check"></i><b>4.3</b> Modelos Sequenciais: Stackelberg</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="interdependencia-estrategica.html"><a href="interdependencia-estrategica.html#apresentação-do-modelo"><i class="fa fa-check"></i><b>4.3.1</b> Apresentação do modelo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="modelo-de-mankiw-e-whinston.html"><a href="modelo-de-mankiw-e-whinston.html"><i class="fa fa-check"></i><b>5</b> Modelo de Mankiw e Whinston</a>
<ul>
<li class="chapter" data-level="5.0.1" data-path="modelo-de-mankiw-e-whinston.html"><a href="modelo-de-mankiw-e-whinston.html#bens-homogêneos"><i class="fa fa-check"></i><b>5.0.1</b> Bens Homogêneos</a></li>
<li class="chapter" data-level="5.0.2" data-path="modelo-de-mankiw-e-whinston.html"><a href="modelo-de-mankiw-e-whinston.html#produtos-diferenciados"><i class="fa fa-check"></i><b>5.0.2</b> Produtos Diferenciados</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Publicado com Bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Organização Industrial</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="interdependencia-estrategica" class="section level1" number="4">
<h1><span class="header-section-number">Capitulo 4</span> Interdependencia Estrategica</h1>
<div id="cartel" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Cartel</h2>
<p>Nesta seção, vamos falar de uma situação em que (1) existem poucas empresas e (2) elas reconhecem esta interdependência e trabalham de forma coordenada para maximizar seus lucros conjuntos.</p>
<p>O grande dilema é como fazer isso funcionar, por duas razões:</p>
<ul>
<li>Isso costuma ser ilegal – ou seja, se as empresas e as pessoas forem pegas fazendo isso, elas vão em cana.</li>
<li>O ``Dilema dos Prisioneiros’’ – há todo o incentivo para que as empresas tentem convencer as outras a participar de um cartel e, ao mesmo tempo, renegar o acordo na forma de descontos secretos.</li>
</ul>
<p>Antes de falarmos o que precisa ser necessário para se implementar um cartel, vamos falar o que <em>NÃO</em> precisa para se conseguir ser um cartel (algumas delas até facilitam, mas não são indispensáveis):</p>
<ul>
<li>Poucas empresas: Um dos setores com maior número de condenações no CADE por cartel é o de Postos de Gasolina</li>
<li>Empresas grandes em relação ao mercado: existe caso até de cartel de padarias no CADE</li>
</ul>
<p>O que é necessário para um cartel funcionar:</p>
<ul>
<li>Coordenar em preços (ou divisão de clientes)</li>
<li>Coordenar a alocação de produção entre os membros do cartel</li>
<li>Observabilidade das ações dos agentes: as empresas que participam do cartel precisam ser capazes de observar as ações (preços, quantidades vendidas)</li>
<li>Capacidade de punição de desvios em relação ao combinado: as empresas que participam do cartel precisam ser capazes de inflingir algum tipo de punição àquelas que não cumprem o que foi prometido.</li>
</ul>
<p>E note-se que estas duas características não são imutavelmente gravadas em pedra - muitos carteis que buscavam sucesso continuado conseguiram estender a vida útil dele por meio de mudanças no comportamento das próprias empresas que permitiam a melhora das duas dimensões – tornar as ações mais observáveis e permitir punições automáticas.</p>
<p>Outro mecanismo que é muito comum e muito empregado para aumentar a ``vida útil’’ dos carteis é o emprego de empresas/associações patronais para permitir que um terceiro realize as atividades de observação dos seus companheiros de cartel. Afinal de contas, não se pode confiar nos seus colegas de crime (pois cartel é crime em muitas jurisdições) para garantir que as ações sejam observadas de forma imparcial, né?</p>
<p>Um exemplo de empresa que (em sua encarnação anterior, AC Treuhand) realizou muitos dos trabalhos necessários para a manutenção de carteis é a ARCO <a href="https://arco.swiss/en">link</a>.</p>
<p><strong>Disclaimer</strong>: Não estou afirmando que esta empresa se envolve em atividades acessórias a crimes de cartel; todavia, nas mãos de um grupo de empresas mal intencionadas, cada um dos serviços ali apresentados pode ser utilizado para aumentar a observabilidade das ações dos comparsas em um cartel.</p>
<div id="história-o-cartel-dos-geradores-de-eletricidade" class="section level3" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> História – o cartel dos geradores de eletricidade</h3>
<p>Este é um texto baseado em parte em um box que está no livro do Carlton e Perloff, sobre o mercado de geradores de eletricidade nos Estados Unidos, ao longo das décadas de 50, 60 e 70.</p>
<p>Nos anos 50, existiam três empresas no mercado de turbinas geradoras de energia:
* Westinghouse
* General Electric
* Allis-Chalmers</p>
<p>As empresas produziam geradores de eletricidade para as companhias geradoras de energia. Essencialmente as companhias preparavam uma planta geradora – tipo uma hidroelétrica – e depois especificavam em detalhe a quantidade e as características dos geradores que iam na barragem. As empresas que vendiam os geradores submetiam suas propostas e as companhias geradoras fechavam com aquela que oferece o menor preço.</p>
<p>Aí no ano de 1959, em uma competição por ofertas para a TVA – Tennessee Valley Authority, um jornalista notou que a oferta vencedora foi de 96,760 dólares (da Westinghouse) e as ofertas das três outras empresas que perderam foram de 112,712 dólares – exatamente as mesmas. Evidentemente, isso é muito esquisito – as empresas são completamente diferentes e produzem seus geradores em lugares e condições completamente diferentes.</p>
<p>Posteriormente, descobriu-se que as empresas já tinham se reunido no Hotel Traymore, em Atlantic City, para dividir o mercado de acordo com a seguinte fórmula:</p>
<ul>
<li>42% para a GE</li>
<li>38% para a Westinghouse</li>
<li>Allis-Chalmers com 11%</li>
<li>I-T-E 9%</li>
</ul>
<p>Eventualmente fizeram alguns ajustes para acomodar alguns entrantes. Mas estes encontros se tornaram regulares e conseguiram manter estas participações por vários anos. O mecanismo do contrato era o mais curioso. Uma empresa – a selecionada pelo cartel – ia colocar o menor preço, e uma era escalada pra cobrar um preço intermediário, e uma terceira pra cobrar o preço alto. A que cobrou um preço mais alto iria, em outra ocasião, cobrar o preço mais baixo, e assim sucessivamente em uma rotação. O mecanismo pelo qual a empresa era selecionada para dar o lance mais baixo – e ganhar – era bastante curioso: as fases da lua. A depender de qual fase a lua se encontrasse na época do certame, uma das empresas era escolhida.</p>
<p>Esta investigação levou a uma condenação depois de dois anos. As empresas foram condenadas a aproximadamente 2 milhões de dólares, as sete pessoas mais importantes foram presas e as outras multadas. Além disso, as empresas prejudicadas pelo cartel entraram com ações de reparação de danos que, ao fim e ao cabo, colocaram o custo disso para as empresas acima de 400 milhões de dólares (dos anos 60!).</p>
<p>Depois dessa condenação, as empresas menores (Allis-Chalmers, I-T-E) saíram do mercado, deixando só a GE e a Westinghouse em uma situação bem complicada – margens pequenas e tendo que lidar com a ressaca da condenação e os custos associados.</p>
<p>No começo dos anos 60, uma nova forma de coordenação foi proposta pela GE,
sem nenhum acordo formal – nem fases da lua. A GE anunciou a seguinte política:</p>
<ul>
<li>Uma nova tabela de preços que simplificava o cálculo dos preços dos produtos para a elaboração dos lances;</li>
<li>Os preços de tabela seriam reduzidos significativamente,
mas;
<ul>
<li>Os preços verdadeiros seriam o valor do preço de tabela multiplicado
por um fator comum, ajustado de forma que mantinha os preços aproximadamente
iguais aos vigentes;</li>
<li>A GE anunciou que venderia a estes preços a todos os consumidores <em>sem exceção</em>.</li>
<li>Uma cláusula de proteção de preços foi instituída, em que, na eventualidade de uma redução de preços, a GE reduziria os preços retroativamente para qualquer consumidor que comprou um gerador nos últimos seis meses;</li>
</ul></li>
<li>Uma empresa de consultoria iria auditar a <strong>compliance</strong> da GE com este acordo;</li>
<li>Os lances colocados pela GE, bem como os pedidos efetivamente feitos, foram tornados públicos</li>
</ul>
<p>Com isso, eles conseguiram elevar suas margens novamente, até serem acusados de cartel novamente nos anos 70.</p>
</div>
<div id="teoria-jogos-repetidos" class="section level3" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Teoria: Jogos Repetidos</h3>
<p>Para que possamos entender teoricamente porque arranjos como o da subseção anterior funcionam, precisamos nos dar conta que a interação estratégica entre as empresas é repetida. Ou seja, ainda que a decisão de preços ou quantidades produzidas tem que ser tomada em cada instante do tempo, o fato é que a empresa vai conviver de forma indefinida com esses oponentes. Neste sentido, o <em>payoff</em> da ação é um valor presente líquido, descontado de acordo com uma taxa que reflita o risco e a expectativa de duração da interação.
Neste sentido, vamos supor que a ação envolve duas coisas – sair do conluio ou se manter nele. Caso a empresa decida se manter no cartel, o valor presente dos lucros seria então:</p>
<p><span class="math display">\[
VP=\frac{\pi_{c}}{1+r}+\frac{\pi_{c}}{(1+r)^{2}}+\cdots=\frac{\pi_{c}}{r}
\]</span></p>
<p>Caso a empresa desvie da solução de conluio, duas coisas provavelmente acontecerão. Em primeiro lugar, ela conseguirá lucros maiores por um tempo – pois os seus oponentes não se dão conta que ela não está mais no acordo. No entanto, quando elas o fazem, elas podem <em>punir</em> a empresa desviante. Ou seja, caso ela desvie da solução de conluio, e consiga lucros adicionais no curto prazo, seguidos de lucros menores depois, temos:</p>
<p><span class="math display">\[
VPC=\frac{\pi_{m}}{1+r}+\frac{\pi_{n}}{(1+r)^{2}}+\cdots
\]</span></p>
<p>Podemos notar que a empresa se mantém interessada no cartel caso <span class="math inline">\(VP&gt;VPC\)</span>.
Isso pode acontecer quando:</p>
<p><span class="math display">\[
\begin{align*}
\pi_{n} &amp; &lt; \pi_{c}\\
\pi_{m} &amp; &gt; \pi_{c}
\end{align*}
\]</span></p>
<p>E quando <span class="math inline">\(r\)</span> baixo o suficiente. A literatura mostra que vários tipos de estratégias de punição são sustentáveis neste sentido, como por exemplo:</p>
<ul>
<li><em>Grim Reaper</em>: uma vez que um dos caras desvia do comportamento colusivo, os outros vão jogar o comportamento competitivo para sempre.</li>
<li><em>Stick and Carrot</em>: uma vez que um dos caras desvia do comportamento colusivo, os outros vão jogar o comportamento colusivo no próximo período.</li>
</ul>
<p>Existe um resultado em jogos repetidos, chamado <em>Teorema Popular</em>,
que afirma que qualquer estratégia – e, conseqüentemente,
os <span class="math inline">\(\pi\)</span> associados – pode ser sustentável como um equilíbrio
de Nash em jogos repetidos, desde que a taxa de desconto seja baixa
o suficiente. Se chama <em>Teorema Popular</em> porque, durante muito tempo, a comunidade dos economistas acreditava e discutia o resultado, mas não havia uma
prova formal do mesmo. Rubinstein (1979) propôs uma prova formal do resultado.</p>
<p>Intuitivamente, isso significa que carteis são mais estaveis quando:</p>
<ul>
<li>É mais fácil descobrir os desvios – a fase de lucros maiores da empresa que desvia dura menos no tempo</li>
<li>A punição é mais forte – ou seja, a perda de lucros é maior na eventualidade de descoberta</li>
<li>O fator de desconto é mais baixo – ou seja, o futuro é mais valioso.</li>
</ul>
</div>
<div id="brasil-legislação-contra-carteis" class="section level3" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> Brasil: Legislação Contra Carteis</h3>
<p>Nesta seção, será revisada a jurisprudência existente sobre carteis. Conforme o art. 37 da Lei 12.529/2001, conforme apresentado por (CADE, 2020) temos as seguintes diretrizes para o estabelecimento de multas:</p>
<p>“I - no caso de empresa, multa de 0,1% (um décimo por cento) a 20% (vinte por cento) do valor do faturamento bruto da empresa, grupo ou conglomerado obtido, no último exercício anterior à instauração do processo administrativo, no ramo de atividade empresarial em que ocorreu a infração, a qual nunca será inferior à vantagem auferida, quando for possível sua estimação;</p>
<p>II - no caso das demais pessoas físicas ou jurídicas de direito público ou privado, bem como quaisquer associações de entidades ou pessoas constituídas de fato ou de direito, ainda que temporariamente, com ou sem personalidade jurídica, que não exerçam atividade empresarial, não sendo possível utilizar-se o critério do valor do faturamento bruto, a multa será entre R$ 50.000,00 (cinquenta mil reais) e R$ 2.000.000.000,00 (dois bilhões de reais);</p>
<p>III - no caso de administrador, direta ou indiretamente responsável pela infração cometida, quando comprovada a sua culpa ou dolo, multa de 1% (um por cento) a 20% (vinte por cento) daquela aplicada à empresa, no caso previsto no inciso I do caput deste artigo, ou às pessoas jurídicas ou entidades, nos casos previstos no inciso II do caput deste artigo.</p>
<p>§ 1o Em caso de reincidência, as multas cominadas serão aplicadas em dobro.”</p>
<p>Além disso, podem ser impostas penalidades que implicam na proibição de se participar em licitações tendo por objeto aquisições, alienações, realização de obras e serviços, concessão de serviços públicos, na administração pública federal, estadual, municipal e do Distrito Federal, bem como em entidades da administração indireta, por prazo não inferior a 5 (cinco) anos (Art. 38).
Quanto à definição de ramo de atividade empresarial, a Resolução do CADE 3/2012 apresenta uma lista de 144 setores de classificação industrial. Se mais de um setor dentre estes for afetado pelo cartel, o CADE geralmente soma o faturamento deles para fins de cálculo de multa. Além disso, a referida resolução inclui o seguinte trecho, conforme (CADE, 2020):</p>
<p>Art. 2º Quando o representado não apresentar o valor do faturamento no(s) ramo(s) de atividade empresarial em que ocorreu a infração de forma completa, inequívoca e idônea, será considerado o faturamento total da empresa ou grupo de empresas, no último exercício anterior à instauração do processo administrativo.</p>
<p>Art. 2-A. O Cade poderá, mediante decisão fundamentada, adaptar o ramo de atividade às especificidades da conduta quando as dimensões indicadas no art. 1º forem manifestamente desproporcionais. (Redação dada pela Resolução nº 18, de 23 de novembro de 2016)</p>
<p>No aspecto criminal, a sanção para casos de cartel está dada pela Lei 8137/1990, no seu art. 4º, que disciplina os Crimes contra a Ordem Econômica, com a seguinte redação:</p>
<p>Art. 4° Constitui crime contra a ordem econômica:</p>
<p>I - abusar do poder econômico, dominando o mercado ou eliminando, total ou parcialmente, a concorrência mediante qualquer forma de ajuste ou acordo de empresas;</p>
<p>II - formar acordo, convênio, ajuste ou aliança entre ofertantes, visando:</p>
<ol style="list-style-type: lower-alpha">
<li><p>à fixação artificial de preços ou quantidades vendidas ou produzidas;</p></li>
<li><p>ao controle regionalizado do mercado por empresa ou grupo de empresas;</p></li>
<li><p>ao controle, em detrimento da concorrência, de rede de distribuição ou de fornecedores.</p></li>
</ol>
<p>Pena - reclusão, de 2 (dois) a 5 (cinco) anos e multa.</p>
<p>Especificamente com relação ao crime de cartel em licitações, o diploma legal relevante é a Lei 8.666/1993, com os seguintes tipos penais:</p>
<p>Art. 90. Frustrar ou fraudar, mediante ajuste, combinação ou qualquer outro expediente, o caráter competitivo do procedimento licitatório, com o intuito de obter, para si ou para outrem, vantagem decorrente da adjudicação do objeto da licitação:</p>
<p>Pena - detenção, de 2 (dois) a 4 (quatro) anos, e multa.</p>
<p>[…]</p>
<p>Art. 95. Afastar ou procurar afastar licitante, por meio de violência, grave ameaça, fraude ou oferecimento de vantagem de qualquer tipo:</p>
<p>Pena - detenção, de 2 (dois) a 4 (quatro) anos, e multa, além da pena correspondente à violência.</p>
<p>Parágrafo único. Incorre na mesma pena quem se abstém ou desiste de licitar, em razão da vantagem oferecida.</p>
<p>Art. 96. Fraudar, em prejuízo da Fazenda Pública, licitação instaurada para aquisição ou venda de bens ou mercadorias, ou contrato dela decorrente:</p>
<p>I - elevando arbitrariamente os preços;</p>
<p>II - vendendo, como verdadeira ou perfeita, mercadoria falsificada ou deteriorada;</p>
<p>III - entregando uma mercadoria por outra;</p>
<p>IV - alterando substância, qualidade ou quantidade da mercadoria fornecida;</p>
<p>V - tornando, por qualquer modo, injustamente, mais onerosa a proposta ou a execução do contrato:</p>
<p>Pena - detenção, de 3 (três) a 6 (seis) anos, e multa</p>
<p>Além disso, o Art. 47 da lei 12.521 também facilita a interposição de ações privadas de reparação de danos de cartel, conforme a redação a seguir:</p>
<p>Art. 47. Os prejudicados, por si ou pelos legitimados referidos no art. 82 da Lei nº 8.078, de 11 de setembro de 1990 , poderão ingressar em juízo para, em defesa de seus interesses individuais ou individuais homogêneos, obter a cessação de práticas que constituam infração da ordem econômica, bem como o recebimento de indenização por perdas e danos sofridos, independentemente do inquérito ou processo administrativo, que não será suspenso em virtude do ajuizamento de ação.</p>
<p>Em resumo, o ordenamento jurídico acima apresentado possui as seguintes características gerais:</p>
<ul>
<li>As multas são baseadas no faturamento:</li>
<li>Do ano anterior à instauração do ilícito</li>
<li>No segmento de atividade em que ocorreu a infração</li>
<li>Possuindo um limite superior</li>
<li>Podendo ser calculada com base no dano causado pelo cartel</li>
<li>Podem ser impostas multas em pessoas físicas</li>
<li>Tanto em casos de cartel de licitações ou carteis que envolvem agentes privados há a possibilidade de sanção criminal.</li>
</ul>
<p>Do ponto de vista de aplicação prática desse marco legal, a referência mais interessante é a tese de Flávia Chiquito dos Santos (SANTOS, 2014), que realiza uma análise de 631 atas de julgamento entre 1996 e 2013. Desta amostra inicial, em apenas 29 casos foi exarada decisão contendo multa de cartel. Deste estudo, alguns aspectos são importantes:</p>
<ul>
<li>94% das multas baseadas em porcentagens foram justificadas;</li>
<li>Em 17% das decisões são apresentadas estimativas da vantagem auferida;</li>
<li>Em 34% das decisões há menção à vantagem auferida;</li>
<li>Média da Multa em casos em que o dano é considerado como severo, mas não há provas diretas da conduta: 3,97%</li>
<li>Média da Multa em casos em que o dano é considerado como severo, e há provas diretas da conduta: 13,28%</li>
<li>Apenas em 3 das 29 decisões o CADE determinou a remessa da sua decisão às autoridades criminais.</li>
<li>Existiam 18 investigações criminais relacionadas à amostra de 29 decisões do CADE</li>
<li>Apenas em um caso o CADE determinou a remessa da decisão a entidade com o fim desta ser capaz de impetrar ações de reparação de danos.</li>
<li>Em quatro casos já existiam ações de reparação de danos correndo em paralelo à decisão do CADE.</li>
</ul>
</div>
<div id="exercício-empírico-o-joint-executive-committee" class="section level3" number="4.1.4">
<h3><span class="header-section-number">4.1.4</span> Exercício Empírico – o <em>Joint Executive Committee</em></h3>
<p>Vamos agora falar de um paper clássico de Rob Porter de 1983 <span class="citation">(<a href="#ref-porter1983study" role="doc-biblioref">Porter 1983</a>)</span> – ``A study in cartel stability: The Joint Executive Committee’’. A ideia do artigo é testar empiricamente uma afirmação clássica de carteis – que são instáveis e que ao longo do tempo você deve observar mudanças de comportamento de colusão (cartel) para competição.</p>
<p>Para isso, o autor usa dados do mercado de frete ferroviário de um cartel. Sobre o funcionamento do artigo, segue a descrição do mesmo retirada diretamente do artigo (em tradução):</p>
<p>``O JEC era um cartel que controlava os embarques de carga para o leste de Chicago para a costa atlântica na década de 1880. Foi formada em abril de 1879 por um acordo das ferrovias envolvidas no mercado. As empresas envolvidas reconheceram publicamente esse acordo, pois ele precedeu a aprovação do Sherman Act (1890) e a formação da Interstate Commerce Commission (1887), que iniciaram a legislação Antitruste nos Estados unidos. Um acordo separado foi feito para carregamentos para o oeste nas mesmas linhas ferroviárias, principalmente por causa das diferenças físicas essenciais dos produtos sendo transportados.</p>
<p>O mecanismo de organização interna adotado pelo JEC era uma variante da estratégia de gatilho. De acordo com Ulen, houve vários casos em que o cartel pensou que tinha ocorrido trapaça, cortou os preços por um tempo e depois voltou ao preço do conluio’’ (<span class="citation">(<a href="#ref-porter1983study" role="doc-biblioref">Porter 1983</a>)</span>, págs. 302-303)</p>
<p>Os autores vão estimar um sistema de equações de oferta e demanda para identificar o efeito do cartel. Do lado de demanda, a equação tem a seguinte forma:</p>
<p><span class="math display">\[
log Q_{t}=\alpha_{0}+\alpha_{1}log p_{t} + \alpha_{2}L_{t}+\varepsilon_{t}
\]</span></p>
<p>Em que <span class="math inline">\(\alpha_{1}\)</span> é a elasticidade-preço da demanda e <span class="math inline">\(L_{t}\)</span> é uma variável <em>dummy</em> com o valor de 1 caso a rota de hidrovia pelos grandes lagos esteja aberta.</p>
<p>A equação de oferta é dada por:</p>
<p><span class="math display">\[
log p_{t}=\beta_{0}+\beta_{1}log Q_{t} + \beta_{2} S_{t} + \beta_{3} I_{t} + \varepsilon_{st}
\]</span></p>
<p>Em que <span class="math inline">\(S_{t}\)</span> é um conjunto de <em>dummies</em> que refletem entrada e saída do mercado, e <span class="math inline">\(I_{t}\)</span> uma <em>dummy</em> que reflete quando o cartel está ativo. O autor, na página 305, afirma que o valor do coeficiente <span class="math inline">\(\beta_{3}\)</span> tem que ser positivo e um pouco menor que <span class="math inline">\(log \left(\frac{\alpha_{1}}{1+\alpha_{1}} \right)\)</span>. As duas equações – demanda e oferta – também incluem <em>dummies</em> de mês, que não são inclusas na apresentação do paper (não sei porquê).</p>
<p>Agora passemos à estimação propriamente dita desse sistema. Iremos usar o método dos Mínimos Quadrados a Dois estágios. Começamos subindo os pacotes usuais, e depois a gente começa a análise.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="interdependencia-estrategica.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readstata13)</span>
<span id="cb23-2"><a href="interdependencia-estrategica.html#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb23-3"><a href="interdependencia-estrategica.html#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb23-4"><a href="interdependencia-estrategica.html#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb23-5"><a href="interdependencia-estrategica.html#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="interdependencia-estrategica.html#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span>
<span id="cb23-7"><a href="interdependencia-estrategica.html#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="interdependencia-estrategica.html#cb23-8" aria-hidden="true" tabindex="-1"></a>data<span class="ot">=</span><span class="fu">read.delim</span>(<span class="st">&quot;./codes/porter.out&quot;</span>, <span class="at">sep=</span><span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span>)</span></code></pre></div>
<p>Neste banco de dados, temos as seguintes variáveis:</p>
<ul>
<li><span class="math inline">\(GR\)</span> - Grain Rate, em dólares por 100 libras.</li>
<li><span class="math inline">\(TQG\)</span> - Total de grão transportado (em toneladas).</li>
<li><span class="math inline">\(LAKES\)</span> - Variável <em>dummy</em>, indicando se os Grandes Lagos estão abertos para navegação.</li>
<li><span class="math inline">\(PO\)</span> - Variável indicado quebra do cartel, com o valor de 1 se há aviso de quebra do cartel na <strong>Railway Review</strong>, e zero caso contrário.</li>
<li><span class="math inline">\(DM1\)</span> - <em>dummy</em> com o valor de 1 da semana 28 em 1880 e 10 de 1883 - refletindo a entrada da <strong>Grand Turk Railway</strong></li>
<li><span class="math inline">\(DM2\)</span> - <em>dummy</em> com o valor de 1 da semana 26 de 1883 a semana 11 em 1886 - refletindo a entrada da <strong>Chicago and Atlantic</strong></li>
<li><span class="math inline">\(DM3\)</span> - <em>dummy</em> com o valor de 1 da semana 12 a 26 de 1886 - quando a <strong>Chicago and Atlantic</strong> saiu do JEC</li>
</ul>
<p>O passo seguinte envolve a construção das variáveis relevantes para o modelo econométrico:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="interdependencia-estrategica.html#cb24-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> data <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="interdependencia-estrategica.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">logq=</span><span class="fu">log</span>(tqg), <span class="at">logp=</span><span class="fu">log</span>(gr), <span class="at">po_price=</span>po<span class="sc">*</span>logp, <span class="at">lakes_dm1=</span>lakes<span class="sc">*</span>dm1,</span>
<span id="cb24-3"><a href="interdependencia-estrategica.html#cb24-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">lakes_dm2=</span>lakes<span class="sc">*</span>dm2, <span class="at">lakes_dm3=</span>lakes<span class="sc">*</span>dm3, <span class="at">lakes_dm4=</span>lakes<span class="sc">*</span>dm4,</span>
<span id="cb24-4"><a href="interdependencia-estrategica.html#cb24-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">lakes_po=</span>lakes<span class="sc">*</span>po)</span></code></pre></div>
<p>Podemos plotar os dados, criando uma figura igual à da página 311 do paper:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="interdependencia-estrategica.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x=</span>week, <span class="at">y=</span>gr)) <span class="sc">+</span></span>
<span id="cb25-2"><a href="interdependencia-estrategica.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code></pre></div>
<div class="figure"><span id="fig:porter03"></span>
<img src="livro_files/figure-html/porter03-1.png" alt="Evolução dos Preços" width="672" />
<p class="caption">
Figure 4.1: Evolução dos Preços
</p>
</div>
<p>A figura acima mostra que temos épocas em que os preços caem pra abaixo da metade dos valores correspondentes ao comportamento de cartel. E eles conseguem marcar essas épocas como relacionadas aos avisos de ``quebra’’ do cartel na revista da associação.</p>
<p>O passo seguinte é estimar as equações de Demanda e Oferta, correspondentes às duas primeiras colunas da Tabela 3 do paper de <span class="citation">(<a href="#ref-porter1983study" role="doc-biblioref">Porter 1983</a>)</span>. Estimaremos as equações separadamente por Variáveis Instrumentais (os autores usam o nome mais antigo de Mínimos Quadrados a dois Estágios).</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="interdependencia-estrategica.html#cb26-1" aria-hidden="true" tabindex="-1"></a>demand<span class="ot">=</span><span class="fu">ivreg</span>(logq<span class="sc">~</span>logp<span class="sc">+</span>lakes<span class="sc">+</span>t1<span class="sc">+</span>t2<span class="sc">+</span>t3<span class="sc">+</span>t4<span class="sc">+</span>t5<span class="sc">+</span>t6<span class="sc">+</span>t7<span class="sc">+</span>t8<span class="sc">+</span>t9<span class="sc">+</span>t10<span class="sc">+</span>t11<span class="sc">+</span>t12 <span class="sc">|</span></span>
<span id="cb26-2"><a href="interdependencia-estrategica.html#cb26-2" aria-hidden="true" tabindex="-1"></a>               dm1<span class="sc">+</span>dm2<span class="sc">+</span>dm3<span class="sc">+</span>dm4<span class="sc">+</span>po<span class="sc">+</span>lakes<span class="sc">+</span>t1<span class="sc">+</span>t2<span class="sc">+</span>t3<span class="sc">+</span>t4<span class="sc">+</span>t5<span class="sc">+</span>t6<span class="sc">+</span>t7<span class="sc">+</span>t8<span class="sc">+</span>t9<span class="sc">+</span>t10<span class="sc">+</span>t11<span class="sc">+</span>t12, <span class="at">data=</span>data)</span>
<span id="cb26-3"><a href="interdependencia-estrategica.html#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="interdependencia-estrategica.html#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(demand)</span></code></pre></div>
<pre><code>## 
## Call:
## ivreg(formula = logq ~ logp + lakes + t1 + t2 + t3 + t4 + t5 + 
##     t6 + t7 + t8 + t9 + t10 + t11 + t12 | dm1 + dm2 + dm3 + dm4 + 
##     po + lakes + t1 + t2 + t3 + t4 + t5 + t6 + t7 + t8 + t9 + 
##     t10 + t11 + t12, data = data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.38281 -0.25400  0.06989  0.27617  1.07333 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  9.17716    0.18385  49.916  &lt; 2e-16 ***
## logp        -0.73494    0.11994  -6.128 2.68e-09 ***
## lakes       -0.43729    0.12024  -3.637 0.000323 ***
## t1          -0.13204    0.11120  -1.187 0.235965    
## t2           0.07704    0.11192   0.688 0.491739    
## t3           0.12174    0.11194   1.088 0.277615    
## t4           0.15419    0.11099   1.389 0.165737    
## t5           0.09443    0.13093   0.721 0.471286    
## t6           0.02452    0.16121   0.152 0.879206    
## t7           0.09627    0.16215   0.594 0.553143    
## t8          -0.25972    0.16176  -1.606 0.109368    
## t9          -0.02256    0.16210  -0.139 0.889390    
## t10          0.13405    0.16476   0.814 0.416473    
## t11          0.18844    0.16226   1.161 0.246377    
## t12          0.20235    0.16025   1.263 0.207628    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3981 on 313 degrees of freedom
## Multiple R-Squared: 0.3097,  Adjusted R-squared: 0.2788 
## Wald test: 8.531 on 14 and 313 DF,  p-value: 1.233e-15</code></pre>
<p>Podemos ver, como no paper, que a elasticidade-preço da demanda é de -0.73, da mesma forma que no paper. Agora olhemos pro lado da oferta:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="interdependencia-estrategica.html#cb28-1" aria-hidden="true" tabindex="-1"></a>supply<span class="ot">=</span><span class="fu">ivreg</span>(logp<span class="sc">~</span>logq<span class="sc">+</span>dm1<span class="sc">+</span>dm2<span class="sc">+</span>dm3<span class="sc">+</span>dm4<span class="sc">+</span>po<span class="sc">+</span>t1<span class="sc">+</span>t2<span class="sc">+</span>t3<span class="sc">+</span>t4<span class="sc">+</span>t5<span class="sc">+</span>t6<span class="sc">+</span>t7<span class="sc">+</span>t8<span class="sc">+</span>t9<span class="sc">+</span>t10<span class="sc">+</span>t11<span class="sc">+</span>t12 <span class="sc">|</span></span>
<span id="cb28-2"><a href="interdependencia-estrategica.html#cb28-2" aria-hidden="true" tabindex="-1"></a>               lakes<span class="sc">++</span>dm1<span class="sc">+</span>dm2<span class="sc">+</span>dm3<span class="sc">+</span>dm4<span class="sc">+</span>po<span class="sc">+</span>t1<span class="sc">+</span>t2<span class="sc">+</span>t3<span class="sc">+</span>t4<span class="sc">+</span>t5<span class="sc">+</span>t6<span class="sc">+</span>t7<span class="sc">+</span>t8<span class="sc">+</span>t9<span class="sc">+</span>t10<span class="sc">+</span>t11<span class="sc">+</span>t12, <span class="at">data=</span>data)</span>
<span id="cb28-3"><a href="interdependencia-estrategica.html#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="interdependencia-estrategica.html#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(supply)</span></code></pre></div>
<pre><code>## 
## Call:
## ivreg(formula = logp ~ logq + dm1 + dm2 + dm3 + dm4 + po + t1 + 
##     t2 + t3 + t4 + t5 + t6 + t7 + t8 + t9 + t10 + t11 + t12 | 
##     lakes + +dm1 + dm2 + dm3 + dm4 + po + t1 + t2 + t3 + t4 + 
##         t5 + t6 + t7 + t8 + t9 + t10 + t11 + t12, data = data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.62580 -0.15968  0.02076  0.14085  0.60218 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -3.9750483  1.7781237  -2.236 0.026097 *  
## logq         0.2529086  0.1730393   1.462 0.144876    
## dm1         -0.2019134  0.0552972  -3.651 0.000306 ***
## dm2         -0.1726670  0.0805900  -2.143 0.032931 *  
## dm3         -0.3186861  0.0647147  -4.924 1.38e-06 ***
## dm4         -0.2081806  0.1721876  -1.209 0.227574    
## po           0.3681081  0.0538476   6.836 4.35e-11 ***
## t1           0.0296711  0.0717509   0.414 0.679505    
## t2           0.0924901  0.0692067   1.336 0.182391    
## t3           0.1296702  0.0711630   1.822 0.069398 .  
## t4          -0.0006216  0.0815621  -0.008 0.993925    
## t5          -0.0425715  0.0757193  -0.562 0.574368    
## t6          -0.0431205  0.0902747  -0.478 0.633231    
## t7          -0.0836778  0.0815187  -1.026 0.305465    
## t8           0.0724364  0.1271474   0.570 0.569293    
## t9           0.0410667  0.0988321   0.416 0.678050    
## t10         -0.1105308  0.0774529  -1.427 0.154569    
## t11         -0.0965937  0.0743072  -1.300 0.194596    
## t12          0.0166324  0.0778148   0.214 0.830889    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2459 on 309 degrees of freedom
## Multiple R-Squared: 0.3163,  Adjusted R-squared: 0.2764 
## Wald test: 13.87 on 18 and 309 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Podemos ver que o coeficiente de interesse, o <span class="math inline">\(\beta_{3}\)</span> na equação de oferta, é estatisticamente diferente de zero, com estimativa pontual de 0.3681. Além disso, os preços no comportamento colusivo são maiores (em média 36.8%) e a entrada de competidores puxa os preços pra baixo.</p>
<p>Finalmente, podemos calcular qual é o chamado <em>parâmetro de conduta</em> – ou seja, a expectativa de como os competidores irão responder a um aumento de uma unidade na sua quantidade produzida. Este parâmetro aqui é igual a 0.2263293. que se comporta de acordo com o que os autores esperam.</p>
</div>
</div>
<div id="oligopólio" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Oligopólio</h2>
<p>Iremos trabalhar um dos principais modelos para entender competição imperfeita, o Modelo de Cournot. Inicialmente iremos fazer uma demonstração mais geral, para depois especializarmos para uma demanda linear.</p>
<div id="resultado-geral" class="section level3" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Resultado geral</h3>
<p>Vamos assumir que existam <span class="math inline">\(n\)</span> empresas neste mercado, cada uma indexada por <span class="math inline">\(i\)</span>. A decisão delas é sobre o quanto produzir, representada por <span class="math inline">\(q_{i}\)</span>. O custo marginal de produção é constante e não necessariamente idêntico entre as empresas.
O preço de mercado é igual para todas as empresas e é o resultado da quantidade <strong>total</strong> produzida, <span class="math inline">\(P=f(\sum_{i=1}^{n} q_{i})=f(Q)\)</span>, de acordo com o que se espera de uma função demanda, <span class="math inline">\(f^{\prime}&lt;0\)</span>. Com essa definição, temos a seguinte expressão para a função receita marginal:</p>
<p><span class="math display">\[
  \begin{aligned}
RT_{i}&amp;=P\times q_{i}\\
RMg_{i}&amp;=\frac{\partial RT_{i}}{\partial q_{i}}=P+q_{i}\times \frac{\partial P}{\partial Q}\times \sum_{j=1}^{n}\frac{\partial q_{j}}{\partial q_{i}}
\end{aligned}
\]</span></p>
<p>A expressão para a receita marginal neste caso pode ser expressa informalmente da seguinte forma. O efeito de um aumento marginal na quantidade produzida é o preço destas unidades marginais produzidas menos o efeito desta quantidade marginal produzida sobre os preços de mercado. A diferença desta expressão em relação à de monopólio é que o efeito final sobre a quantidade total depende do aumento da própria empresa <span class="math inline">\(i\)</span> e de o que a empresa <span class="math inline">\(i\)</span> considera que seus oponentes <span class="math inline">\(j\neq i\)</span> farão em resposta à ação de <span class="math inline">\(i\)</span> – daí esses componentes da somatória serem também conhecidos como ``variações conjecturais’’.</p>
<p>Estas variações conjecturais são conhecidas desde os anos 60 do século passado; todavia, apenas com a formalização em teoria dos jogos que se conseguiu mapear de forma mais organizada o que se entende ou se espera destas variações conjecturais. Basicamente, aqui iremos utilizar o conceito de equilíbrio de Nash para a determinação do equilíbrio – o que faz com que esta função receita marginal seja base para a construção das Funções Melhor Resposta.</p>
<p>Basicamente, a melhor resposta para uma firma <span class="math inline">\(i\)</span> vai ser a escolha de quantidades para esta empresa que maximiza seus lucros assumindo que as quantidades dos seus oponentes sejam constantes.</p>
<p>Com esta premissa, temos:</p>
<p><span class="math display">\[
  \begin{aligned}
\frac{\partial q_{j}}{\partial q_{i}}&amp;=0,j\neq i\\
\frac{\partial q_{j}}{\partial q_{i}}&amp;=1,j= i\\
\end{aligned}
\]</span></p>
<p>Com isso, a função melhor resposta fica sendo:</p>
<p><span class="math display">\[
  \begin{aligned}
RMg_{i}-CMg_{i}&amp;=0\\
P-CMg_{i}+q_{i}\times \frac{\partial P}{\partial Q}&amp;=0\\
\frac{P-CMg_{i}}{P}&amp;=\frac{q_{i}}{Q}\times \frac{1}{|\varepsilon_{D}|}=\frac{s_{i}}{|\varepsilon_{D}|}
\end{aligned}
\]</span></p>
<p>Supondo que esta condição valha para cada uma das empresas, temos que as margens preço-lucro aqui são iguais à razão entre a participação de mercado e o valor absoluto da elasticidade-preço da demanda. Intuitivamente, empresas mais eficientes (com menores custos marginais) tem maiores margens preço-custo marginal e maiores participações de mercado.</p>
<p>Outro resultado interessante acontece quando tentamos calcular a margem preço-custo média da indústria:</p>
<p><span class="math display">\[
  \begin{aligned}
\sum_{i=1}^{n}s_{i} \times \frac{P-CMg_{i}}{P}&amp;=\sum_{i=1}^{n}\frac{s_{i}^{2}}{|\varepsilon_{D}|}\\
\frac{P-\overline{CMg_{i}}}{P}&amp;=\frac{HHI}{|\varepsilon_{D}|}
\end{aligned}
\]</span>
Em que <span class="math inline">\(HHI\)</span> é o chamado Índice Herfindahl-Hirschman. Se as premissas do modelo de Cournot forem válidas (competição por quantidades, produtos homogêneos), uma forma de avaliar a competitividade em um mercado sem ter que descobrir quais seriam os custos marginais é simplesmente calcular o Índice Herfindahl-Hirschman.</p>
</div>
<div id="exemplo-demanda-linear" class="section level3" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Exemplo: Demanda Linear</h3>
<p>Vamos agora assumir uma demanda e custos marginais lineares, e duas empresas. A vantagem dessa abordagem é que ela permite que apresentamos as coisas de forma gráfica. Como anteriormente, vamos assumir que a demanda inversa é uma função das quantidades produzidas das duas empresas</p>
<p><span class="math display">\[
  P=a-b(q_{1}+q_{2})
\]</span>
Como disse anteriormente, os custos marginais são constantes, o que significa que <span class="math inline">\(CT_{i}=c_{i}\times q_{i}, i=1,2\)</span>.</p>
<p>As funções lucro das empresas 1 e 2 são da seguinte forma então:</p>
<p><span class="math display">\[
  \begin{aligned}
\pi_{i}&amp;=(P-c_{i})q_{i}=(a-b(q_{1}+q_{2})-c_{i})q_{i}\\
\pi_{1}&amp;=(P-c_{1})q_{1}=(a-b(q_{1}+q_{2})-c_{1})q_{1}\\
\pi_{2}&amp;=(P-c_{2})q_{2}=(a-b(q_{1}+q_{2})-c_{2})q_{2}
\end{aligned}
\]</span></p>
<p>Podemos construir duas coisas a partir das funções lucro <span class="math inline">\(\pi_{i}\)</span>: as funções isolucro e as funções melhor resposta. A primeira delas é o lugar geométrico dos pontos correspondentes a um determinado nível de lucro, e a segunda diz, para uma determinada quantidade de uma das empresas, quanto o seu oponente deveria produzir para maximizar seus lucros.</p>
<p>Esta última podemos derivar a partir das condições de primeira ordem:</p>
<p><span class="math display">\[
  \frac{\partial \pi_{1}}{\partial q_{1}}=(a-2bq_{1}-bq_{2}-c_{1})=0
\]</span></p>
<p>Reorganizando, chegamos às seguintes funções melhor resposta:</p>
<p><span class="math display">\[
  \begin{aligned}
q_{1}&amp;=\frac{a-bq_{2}-c_{1}}{2b}\\
q_{2}&amp;=\frac{a-bq_{1}-c_{2}}{2b}
\end{aligned}
\]</span></p>
<p>O equilíbrio de Nash deste jogo acontece quando temos as duas funções melhor resposta valendo simultaneamente. Ou seja, quando resolvemos o sistema de duas equações em duas incógnitas. Supondo custos marginais constantes, temos as seguintes quantidades e preço de equilíbrio:</p>
<p><span class="math display">\[
  \begin{aligned}
q_{1}=q_{2}&amp;=\frac{a-c}{3b}\\
Q&amp;=2\frac{a-c}{3b}\\
P&amp;=\frac{a+2c}{3}
\end{aligned}
\]</span></p>
<p>Primeira coisa interessante deste modelo de Cournot é que ele consegue representar um ``caminho intermediário’’ entre o monopólio e competição perfeita. Por exemplo, em um mercado monopolizado, teríamos o seguinte:</p>
<p><span class="math display">\[
  \begin{aligned}
Q&amp;=\frac{a-c}{2b}\\
P&amp;=\frac{a+c}{2}
\end{aligned}
\]</span></p>
<p>Esta seria a quantidade de equilíbrio que um cartel que buscasse maximizar os lucros também produziria. Supondo firmas idênticas, teríamos <span class="math inline">\(q_{i}=\frac{a-c}{4b}\)</span>. O problema é que esta configuração não é um equilíbrio estável. Se as duas empresas estiverem produzindo isso, a melhor resposta de uma delas é aumentar um pouco sua produção.</p>
<p>O segundo ponto interessante é que o modelo de Cournot mantém essa característica de ``caso intermediário’’ à medida em que variamos o número de empresas.</p>
</div>
<div id="modelo-de-cournot-com-muitas-firmas" class="section level3" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Modelo de Cournot com muitas firmas</h3>
<p>Usando a mesma forma de demanda e custos, apenas assumindo que as firmas são idênticas e que ao invés de duas, existem <span class="math inline">\(n\)</span> empresas. A função demanda fica sendo então:</p>
<p><span class="math display">\[
  P=a-b(\sum_{j=1}^{n}q_{j})
\]</span></p>
<p>A função lucro de uma firma específica fica então sendo:</p>
<p><span class="math display">\[
  \pi_{i}=(a-b(\sum_{j=1}^{n}q_{j})-c)q_{i}
\]</span></p>
<p>Vamos ter as seguintes Condições de Primeira Ordem:</p>
<p><span class="math display">\[
  \frac{\pi_{i}}{q_{i}}=a-b(\sum_{j=1}^{n}q_{j})-bq_{i}-c=0
\]</span></p>
<p>Reorganizando, chegamos à seguinte função melhor resposta para a empresa genérica <span class="math inline">\(i\)</span>:</p>
<p><span class="math display">\[
  q_{i}=\frac{a-b\sum_{j=1}^{n}q_{j}-c}{b}
\]</span></p>
<p>Se as empresas são iguais, espera-se que elas em equilíbrio produzam a mesma coisa, ou seja, <span class="math inline">\(q_{i}=q_{j}=q^{*}\)</span></p>
<p><span class="math display">\[
  \begin{aligned}
q^{*}&amp;=\frac{a-bnq^{*}-c}{b}\\
q^{*}&amp;=\frac{1}{n+1}\frac{a-c}{b}\\
Q=nq^{*}&amp;=\frac{n}{n+1}\frac{a-c}{b}\\
P=&amp;\frac{a}{n+1}+c\frac{n}{n+1}
\end{aligned}
\]</span></p>
<p>Com <span class="math inline">\(n\rightarrow \infty\)</span>, temos que a solução se aproxima de competição perfeita.</p>
<p>## Introdução</p>
<p>Neste texto, iremos analisar o modelo inicialmente desenvolvido por Joseph Bertrand como uma resposta às conclusões do Modelo de Cournot. Dentro deste modelo, a principal variável estratégica utilizada são os preços cobrados pelas empresas envolvidas</p>
</div>
<div id="exposição-inicial" class="section level3" number="4.2.4">
<h3><span class="header-section-number">4.2.4</span> Exposição Inicial</h3>
<p>Vamos supor a existência de duas firmas e que não exista diferenciação de produto. Ou seja, os produtos são substituíveis aos olhos do consumidor e, tendo em vista que eles conhecem os preços dos dois produtores, eles irão comprar do produtor de menor preço.
Caso as duas empresas cobrem o mesmo preço, elas dividirão o mercado igualmente. Considerando uma função demanda de mercado dada por <span class="math inline">\(Q=D(P)\)</span>, e supondo que cada firma tenha um custo marginal constante e igual a <span class="math inline">\(c\)</span>, temos que a função lucro para a firma <span class="math inline">\(i=1,2\)</span> igual a:</p>
<p><span class="math display">\[
\pi_{i}(p_{i},p_{j})=(p_{i}-c)\times D_{i}(p_{i},p_{j})
\]</span></p>
<p>Coloquei o subscrito <span class="math inline">\(i\)</span> na função demanda porque é a quantidade de cada empresa. Mais especificamente, temos:</p>
<p><span class="math display">\[
D_{i}=\begin{cases} D(p_{i}), \quad p_{i}&lt;p_{j}\\ \frac{D(p_{i})}{2}, \quad p_{i}=p_{j}\\
0,\quad p_{i}&gt;p_{j} \end{cases}
\]</span>
Além disso, podemos afirmar que o lucro agregado de mercado, <span class="math inline">\(\pi_{1}+\pi_{2}\)</span> é menor do que o lucro que aconteceria se o mercado fosse monopolizado. Além disso, não há situação em que a empresa cobre um preço maior do que o custo marginal e ganhe lucros negativos. Estas duas premissas são necessárias somente para que a gente garanta que não exista uma configuração esquisita de mercado em que exista apenas uma empresa.</p>
<div id="o-paradoxo-de-bertrand" class="section level4" number="4.2.4.1">
<h4><span class="header-section-number">4.2.4.1</span> O “Paradoxo de Bertrand”</h4>
<p>Vamos mostrar agora um teorema, que deu margem ao chamado “Paradoxo de Bertrand.” Para esta demonstração, vamos usar novamente os conceitos de Teoria dos Jogos e caracterizar este equilíbrio como também um Equilíbrio de Nash.</p>
<p>Um equilíbrio de Nash é um conjunto de configurações de estratégias (no nosso caso, preços) tal que cada uma delas é uma melhor resposta às estratégias dos seus oponentes.</p>
<p>Com isso, podemos afirmar o seguinte teorema:</p>
<p><strong>O Jogo acima exposto somente admite um Equilíbrio de Nash em estratégias puras,em que cada empresa cobra um preço exatamente igual ao custo marginal, isto é, <span class="math inline">\(p_{1}^{*}=p_{2}^{*}=c\)</span></strong></p>
<p>A demonstração é a seguinte:</p>
<p>Vamos começar imaginando que isso não seja verdade, e que exista um equilíbrio de Nash em que esta condição não se verifique. Mostraremos que cada uma das possibilidades leva a uma contradição.
Caso 01: Suponha que <span class="math inline">\(p_{1}&gt;p_{2}&gt;c\)</span>. Neste caso, a firma 1 não vende nada e o seu lucro é zero. Por outro lado, se a firma 1 abaixar o seu preço para <span class="math inline">\(p_{1}=p_{2}^{*}-\varepsilon\)</span>, com <span class="math inline">\(\varepsilon\)</span> positivo e pequeno, ela teria a demanda completa do mercado a este preço, <span class="math inline">\(D(p_{2}^{*}-\varepsilon)\)</span> e obteria uma margem positiva igual a <span class="math inline">\(p_{2}^{*}-\varepsilon-c\)</span>. Portanto, a firma 1 não poderia estar maximizando seus lucros para o preço de 2 igual a <span class="math inline">\(p_{2}^{*}\)</span>, ou seja isso não pode ser uma parte do equilíbrio de Nash.
Vamos agora supor que <span class="math inline">\(p_{1}^{*}=p_{2}^{*}&gt;c\)</span>. Neste caso, o lucro da firma 1 seria <span class="math inline">\(\frac{D(p_{1}^{*})(p_{1}^{*}-c)}{2}\)</span>. Se a firma 1 cobrasse um preço igual a <span class="math inline">\(p_{1}=p_{2}^{*}-\varepsilon\)</span>, o seu lucro seria então <span class="math inline">\(D(p_{2}^{*}-\varepsilon)(p_{1}-c)\)</span>, que é maior – se continuarmos a considerar um <span class="math inline">\(\varepsilon\)</span> pequeno.</p>
<p>Neste caso, a participação de mercado da firma aumentaria de uma forma descontínua. Uma vez que nenhuma firma iria cobrar um preço inferior ao custo marginal <span class="math inline">\(c\)</span>, a única solução possível é que pelo menos uma das firmas cobre exatamente este custo.</p>
<p>Finalmente, caso tivéssemos <span class="math inline">\(p_{1}^{*}&gt;p_{2}^{*}=c\)</span>, a firma 2 poderia aumentar os seus preços para um <span class="math inline">\(\varepsilon\)</span> pra baixo de <span class="math inline">\(p_{1}\)</span>, continuar atendendo todo o mercado e aumentar os seus lucros. Portanto, esta configuração também não é um equilíbrio. Portanto, o teorema está provado.</p>
<p>Este resultado é chamado “Paradoxo de Betrand” porque leva a uma conclusão, bem, paradoxal: um duopólio, sem competidores adicionais, levando a resultados idênticos à de competição perfeita.</p>
<p>Como todo resultado aparentemente paradoxal, a importância dele reside em ressaltar quais são as condições necessárias para que ele valha, permitindo que a gente relaxe estas premissas uma por vez e chegue em vários resultados interessantes.</p>
<p>As premissas relevantes são:</p>
<ul>
<li>Produtos Homogêneos</li>
<li>Cada empresa é capaz de atender sozinha o mercado se for a empresa com o preço mais barato</li>
<li>Estamos nos atendo a equilíbrios em estratégias puras</li>
<li>Todos os (dois) preços são conhecidos por todos os consumidores</li>
</ul>
<p>Ao longo das próximas aulas, iremos falar de extensões deste modelos em todas as direções.</p>
</div>
</div>
<div id="bertrand-com-produtos-diferenciados" class="section level3" number="4.2.5">
<h3><span class="header-section-number">4.2.5</span> Bertrand com Produtos Diferenciados</h3>
<p>Vamos assumir que os produtos sejam diferenciados aos olhos dos consumidores. Tal diferenciação não necessariamente precisa coincidir com alguma caracterização física diferente.</p>
<p>Suponhamos que a quantidade vendida pela empresa <span class="math inline">\(i\)</span> seja dada pela seguinte equação:</p>
<p><span class="math display">\[
q_{i}=\alpha-\beta p_{i} + \gamma p_{j}
\]</span></p>
<p>Podemos denotar o <em>grau de diferenciação</em> de uma marca como sendo <span class="math inline">\(\delta= \frac{\gamma^{2}}{\beta^{2}}\)</span>.</p>
<p>Caso as marcas sejam <strong>fortemente diferenciadas</strong>, temos que os produtos são altamente diferentes aos olhos dos consumidores, de tal forma que uma mudança no preço da marca <span class="math inline">\(j\)</span> tem pouco efeito sobre a demanda de <span class="math inline">\(i\)</span>. Ou seja, <span class="math inline">\(\delta\rightarrow 0\)</span> e <span class="math inline">\(\gamma \rightarrow 0\)</span>.</p>
<p>Por outro lado, se as marcas forem <strong>quase homogêneas</strong>, temos que o efeito cruzado dos preços é quase igual ao efeito próprio. Isso significa que um aumento no preço do produto <span class="math inline">\(j\)</span> terá um efeito sobre a quantidade do produto <span class="math inline">\(i\)</span> quase igual (em valores absolutos) ao efeito que o preço do próprio produto <span class="math inline">\(i\)</span> tem sobre sua quantidade. Neste caso, <span class="math inline">\(\delta\rightarrow 1\)</span>, ou <span class="math inline">\(\gamma=\beta\)</span>.</p>
<p>Vamos começar caracterizando então como é a interação estratégica entre estas empresas. Supondo custos marginais constantes e iguais a <span class="math inline">\(c\)</span>, chegamos à seguinte função lucro para a empresa <span class="math inline">\(i\)</span>:</p>
<p><span class="math display">\[
\pi_{i}=(p_{i}-c)\times(\alpha - \beta p_{i} + \gamma p_{j})
\]</span></p>
<p>Isso leva à seguinte condição de primeira ordem:
<span class="math display">\[
\frac{\partial \pi_{i}}{\partial p_{i}}=\alpha-2\beta p_{i} + \gamma p_{j} +c \beta =0
\]</span></p>
<p>Reorganizando, chegamos à seguinte Função Melhor Resposta para a empresa <span class="math inline">\(i\)</span>:</p>
<p><span class="math display">\[
p_{i}=\frac{\alpha+\gamma p_{j}+c\beta}{2\beta}
\]</span></p>
<p>Um ponto importante é que estas funções melhor resposta são positivamente inclinadas – ou seja, a melhor resposta a um preço maior do seu oponente é aumentar o seu preço. No modelo de Cournot essas funções melhor resposta eram negativamente inclinadas. Nesta literatura, quando temos as FMR positivamente inclinadas dizemos que as variáveis são “substitutos estratégicos”" e quando elas são negativas elas são “complementos estratégicos.” Podemos mostrar que esta diferença é importante quando passamos de um jogo simultâneo para um jogo sequencial.</p>
<p>Evidentemente, temos uma Função melhor resposta simétrica que gera um sistema de equações. Resolvendo o sistema associado e substituindo a Função Melhor Resposta da firma <span class="math inline">\(j\)</span> na FMR da firma <span class="math inline">\(i\)</span>, temos:</p>
<p><span class="math display">\[
\begin{aligned}
p_{i}^{*}&amp;=\frac{\alpha+c\beta}{2\beta}+\frac{\gamma}{2\beta} \left( \frac{\alpha+\gamma p_{i}^{*} + c\beta}{2\beta} \right)\\
4\beta^{2} p_{i}^{*} &amp;= 2\alpha\beta+2c\beta^{2} + \alpha\gamma + \gamma^{2}p_{i}^{*}+c\gamma \beta\\
p_{i}^{*}(4\beta^{2}-\gamma^{2})&amp;=\alpha(2\beta+\gamma)+c\beta(2\beta+\gamma)\\
p_{i}&amp;=\frac{\alpha+c\beta}{2\beta-\gamma}
\end{aligned}
\]</span></p>
<p>Podemos mostrar (e considerando que, para que este sistema admita representação inversa, que <span class="math inline">\(\alpha\)</span> é uma função tal que <span class="math inline">\(\alpha\rightarrow 0\)</span> quando <span class="math inline">\(\beta \rightarrow \gamma\)</span> – ver SHY, p. 135 e apêndice 7.4), que o preço tende ao custo marginal quando <span class="math inline">\(\gamma\rightarrow \beta\)</span>, ou seja, os produtos ficam cada vez mais homogêneos.</p>
<p>A quantidade vendida da empresa <span class="math inline">\(i\)</span>, em um equilíbrio simétrico, é dada por:</p>
<p><span class="math display">\[
\begin{aligned}
q_{i}&amp;=\alpha-(\beta-\gamma)\left(\frac{\alpha+c\beta}{2\beta-\gamma} \right)\\
q_{i}&amp;=\frac{\alpha(2\beta-\gamma) -\alpha\beta-c\beta^{2}+\alpha\gamma+c\gamma\beta}{2\beta-\gamma}\\
q_{i}&amp;=\frac{\alpha\beta+c\beta(\gamma-\beta)}{2\beta-\gamma}
\end{aligned}
\]</span></p>
<p>Podemos notar que a quantidade vai para zero também quanto menor a diferenciação entre os produtos.</p>
<p>Poderíamos fazer uma derivação similar para o caso de competição à la Cournot. Só que ela não tem interesse por si só. A única questão que vale a pena é a comparação entre os resultados de Cournot com produtos diferenciados e os resultados de Bertrand com produtos diferenciados discutida acima. Essas diferenças entre qual seria o preço de uma empresa <span class="math inline">\(i\)</span> em cada caso, <span class="math inline">\(p_{i}^{b}\)</span> e <span class="math inline">\(p_{i}^{c}\)</span> podem ser resumidas na seguinte proposição, derivada de Vives 1985:</p>
<p><em>Proposição</em> Em uma indústria com produtos diferenciados:</p>
<ul>
<li>O preço de uma empresa <span class="math inline">\(i\)</span> seria maior em uma competição Cournot do que em uma competição Bertrand, ou seja <span class="math inline">\(p_{i}^{c}&gt;p_{i}^{b}\)</span>.</li>
<li>Quanto mais diferenciados os produtos, menor seria a diferença entre os resultados de uma competição Cournot e os de uma competição Bertrand, ou seja, <span class="math inline">\(\frac{\partial (p_{i}^{c}-p_{i}^{b})}{\partial \gamma}&gt;0\)</span></li>
<li>A diferença tende a zero quando os produtos são independentes, ou seja, <span class="math inline">\(\lim_{\gamma \rightarrow 0}(p_{i}^{c}-p_{i}^{b})=0\)</span></li>
</ul>
<p>A intuição para estes resultados é a seguinte. Uma vez que na competição de Cournot as empresas esperam que as suas oponentes mantenham suas quantidades constantes, uma elevação unilateral das quantidades produzidas levará a uma redução nos preços, e por isso elas se abstêm de aumentar as quantidades. Por outro lado, na competição Bertrand, como as empresas assumem em suas funções melhor resposta que seus oponentes manterão seus preços constantes, elas aumentam mais sua produção, puxando os preços um pouco mais para baixo.</p>
</div>
<div id="jogos-sequenciais-em-bertrand" class="section level3" number="4.2.6">
<h3><span class="header-section-number">4.2.6</span> Jogos sequenciais em Bertrand</h3>
<p>Neste caso, a derivação de um jogo sequencial para a competição de Bertrand com produtos diferenciados é que é pouco relevante. A mecânica é a mesma, resolvendo a FMR da seguidora e substituindo na função objetivo da empresa líder. No entanto, ocorre o seguinte resultado:</p>
<ul>
<li>As duas empresas auferem lucros maiores neste jogo sequencial do que no jogo simultâneo acima.</li>
<li>A firma que se move primeiro tem um lucro <em>menor</em> do que a firma que se move depois.</li>
<li>O aumento de lucros para a firma seguidora é maior do que o aumento de lucros para a firma líder.</li>
</ul>
<p>Intuitivamente, a lógica desta proposição é a seguinte. A empresa líder sabe que a seguidora irá cobrar preços um pouco mais baixos que ela. Portanto, sabendo disso, ela irá cobrar preços mais altos que no equilíbrio em jogos simultâneos, para evitar que a seguidora coloque um preço baixo demais e roube consumidores demais. Ou seja, as duas empresas cobram preços acima dos de equilíbrio no jogo simultâneo. Como a empresa seguidora vai cobrar o preço um pouco mais baixo que a empresa líder, ela tem os lucros relativamente maiores.</p>
</div>
<div id="bertrand-multiproduto" class="section level3" number="4.2.7">
<h3><span class="header-section-number">4.2.7</span> Bertrand Multiproduto</h3>
<p>O <em>insight</em> deste tipo de modelo, com competição oligopolística com produtos diferenciados, é poderoso o suficiente para que possamos inclusive usá-lo para prever os efeitos que eventuais operações de fusão tem sobre os preços.</p>
<p>Aqui adaptaremos um código que o pessoal do DOJ (<em>Department of Justice</em>) dos EUA utilizou no seu pacote <code>antitrust</code>. Vamos entender isso melhor.</p>
<div id="caso-com-n-empresas-de-produto-único" class="section level4" number="4.2.7.1">
<h4><span class="header-section-number">4.2.7.1</span> Caso com <span class="math inline">\(N\)</span> empresas de produto único</h4>
<p>Vamos começar com o caso mais simples, onde existam <span class="math inline">\(N\)</span> empresas, potencialmente diferentes com seus custos marginais, cada uma produzindo apenas um bem. Neste caso, a função lucro de uma empresa <span class="math inline">\(i\)</span> é dada por:</p>
<p><span class="math display">\[
\pi_{i}=(p_{i}-c_{i})q_{i}(\mathbf{p})
\]</span></p>
<p>Em que <span class="math inline">\(\mathbf{p}\)</span> é o vetor de preço dos <span class="math inline">\(N\)</span> produtos. Cada empresa/produto escolhe seus preços a partir das condições de primeira ordem:</p>
<p><span class="math display">\[
\frac{\partial \pi_{i}}{\partial p_{i}}=q_{i} + (p_{i}-c_{i})\frac{\partial q_{i}}{\partial p_{i}}=0
\]</span></p>
<p>Reorganizando, temos a seguinte expressão para a CPO:</p>
<p><span class="math display">\[
\begin{aligned}
1+\left( \frac{p_{i}-c_{i}}{p_{i}} \times \frac{\partial q_{i}}{\partial p_{i}}\frac{p_{i}}{q_{i}} \right)=0\\
1+\left( \frac{p_{i}-c_{i}}{p_{i}} \times \epsilon_{ii} \right)=0
\end{aligned}
\]</span></p>
<p>Como todas estas CPO’s precisam ser satisfeitas, podemos representar em forma matricial este sistema da seguinte forma:</p>
<p><span class="math display">\[
\mathbf{1}+(\mathbb{E}\odot \mathbf{I})(\mathbf{m})=\mathbf{0}
\]</span></p>
<p>Em que <span class="math inline">\(\mathbf{1}\)</span> é um vetor coluna de 1’s, <span class="math inline">\(\mathbb{E}\)</span> uma matriz <span class="math inline">\(N\times N\)</span> de elasticidades, <span class="math inline">\(\mathbf{I}\)</span> a matriz identidade e <span class="math inline">\(\mathbf{m}\)</span> um vetor coluna de índices de Lerner para cada um dos produtos. O operador <span class="math inline">\(\odot\)</span> é o chamado “Operador Hadamard,” ou multiplicação de matrizes elemento por elemento.
Calculando ou calibrando as elasticidades, podemos calcular as margens observadas reorganizando este sistema de equações da seguinte forma:</p>
<p><span class="math display">\[
\mathbf{m}=-(\mathbb{E}\odot \mathbf{I})^{-1}\mathbf{1}
\]</span>
Como os preços e quantidades são observados, sabendo as elasticidades conseguimos calcular os custos marginais de cada produto.</p>
<p>Vamos agora analisar o caso em que uma empresa produza 2 produtos, sendo que os outros <span class="math inline">\(N-2\)</span> produtos são oferecidos pelas outras empresas.</p>
</div>
<div id="uma-empresa-multiproduto" class="section level4" number="4.2.7.2">
<h4><span class="header-section-number">4.2.7.2</span> Uma empresa multiproduto</h4>
<p>Neste caso, a empresa no momento em que ela decide escolher o preço da empresa 1, tem que levar em conta que irá afetar as vendas da outra marca que possui. Ou seja, se aumentar os preços de um dos produtos, alguns dos consumidores irão fugir para outro dos produtos da mesma empresa. Isso faz com que as condições de primeira ordem se tornem:</p>
<p><span class="math display">\[
\begin{aligned}
\frac{\partial \pi_{1}}{\partial p_{1}}&amp;=q_{1} + (p_{1}-c_{1})\frac{\partial q_{1}}{\partial p_{1}}+(p_{2}-c_{2})\frac{\partial q_{2}}{\partial p_{1}}=0\\
&amp;=p_{1}q_{1}+\frac{p_{1}-c_{1}}{p_{1}}\epsilon_{11}q_{1}p_{1} + \frac{p_{2}-c_{2}}{p_{2}}\epsilon_{12}q_{2}p_{2}=0
\end{aligned}
\]</span></p>
<p>Dividindo os dois lados da CPO pelo valor total da receita de vendas <span class="math inline">\(p_{1}q_{1}+p_{2}q_{2}\)</span>, temos então o seguinte:</p>
<p><span class="math display">\[
s_{1}+\left(\frac{p_{1}-c_{1}}{p_{1}} \right)\epsilon_{11}s_{1}+ \left( \frac{p_{2}-c_{2}}{p_{2}}\right)\epsilon_{21}s_{2} =0
\]</span></p>
<p>Podemos representar este sistema de condições de primeira ordem, na forma matricial, da seguinte forma:</p>
<p><span class="math display">\[
\mathbf{s}+(\mathbb{E}\odot \mathbf{\Omega})(\mathbf{m} \odot \mathbf{s})=\mathbf{0}
\]</span></p>
<p>As diferenças neste caso reside nas matrizes <span class="math inline">\(\Omega\)</span> (que é uma matriz de zeros e uns, representando quais produtos são oferecidos pela mesma empresa) e o vetor coluna <span class="math inline">\(\mathbb{s}\)</span>, que é um “empilhamento” dos shares das receitas dos produtos para as empresas (e que necessariamente será igual a um no caso da empresa que só faz um produto).</p>
<p>Reorganizando o sistema de equações, podemos encontrar a seguinte expressão para os produtos:</p>
<p><span class="math display">\[
\mathbb{m}=-(\mathbb{E}\odot \mathbf{\Omega})^{-1} \mathbf{s} \odot (\frac{1}{\mathbf{s}})
\]</span></p>
<p>Com isso, a gente consegue simular os efeitos de uma operação de fusão entre as empresas. Vamos usar o aplicativo <code>shiny</code> deste pacote para isso.</p>
<pre><code>## Loading required package: antitrust</code></pre>
<pre><code>## 
## Attaching package: &#39;antitrust&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:car&#39;:
## 
##     logit</code></pre>
<pre><code>## Loading required package: trade</code></pre>
<pre><code>## Loading required package: rhandsontable</code></pre>
<pre><code>## 
## Attaching package: &#39;competitiontoolbox&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:trade&#39;:
## 
##     trade_shiny</code></pre>
<pre><code>## The following object is masked from &#39;package:antitrust&#39;:
## 
##     antitrust_shiny</code></pre>
<p>O pacote é flexível o suficiente para que possamos caracterizar vários equilíbrios sob um monte de modelos diferentes.</p>
<p><div style="width: 100% ; height: 700px ; text-align: center; box-sizing: border-box; -moz-box-sizing: border-box; -webkit-box-sizing: border-box;" class="muted well">Shiny applications not supported in static R Markdown documents</div></p>
</div>
</div>
<div id="bertrand-com-restrições-de-capacidade" class="section level3" number="4.2.8">
<h3><span class="header-section-number">4.2.8</span> Bertrand com restrições de capacidade</h3>
<p>A hipótese de diferenciação de produtos como forma de sair do “paradoxo de Bertrand” é muito útil, mas não é o único caminho. Outra linha teórica envolve assumir a existência de limites de capacidade – ou seja, as empresas são capazes de atender aos consumidores até certo ponto.</p>
<p>Esta abordagem tem alguns limites, no sentido que não necessariamente gera conclusões robustas às premissas. Dependendo dos tamanhos relativos das capacidades e de como os consumidores são selecionados para serem atendidos pela empresa com preço mais barato, pode não haver equilíbrio em estratégias puras. Este fenômeno foi reconhecido por F. Y. Edgeworth em 1995, dando margem aos chamados “Ciclos de Edgeworth.”</p>
<p>No presente texto, iremos adotar uma versão deste modelo em que existe um equilíbrio de Nash em estratégias puras.</p>
<p>A estrutura é a mais simples, duas empresas <span class="math inline">\(i=1,2\)</span>. Cada uma delas tem um custo marginal constante e igual a <span class="math inline">\(c\)</span>, até um nível de capacidade <span class="math inline">\(K\)</span>. A partir daí, o custo marginal tende ao infinito.</p>
<p>Vamos supor inicialmente a seguinte função demanda:</p>
<p><span class="math display">\[
P=a-b(q_{1}+q_{2})
\]</span>
A Função Demanda Residual da empresa 1 é dada por <span class="math inline">\(q_{1}=\frac{a}{b}-K-\frac{P_{1}}{b}\)</span>
Este modelo vai ter um monte de descontinuidades, então vou ter que examinar os equilíbrios de Nash por meio das <em>funções melhor resposta</em> Para a empresa 1, a FMR fica sendo:</p>
<p><span class="math display">\[
q_{i}=\begin{cases} min \left[ \frac{a}{b}-K-\frac{1}{b}P_{1}, K \right] \quad se \quad P_{2}&lt;P_{1} \leq a-bK \\ \frac{1}{2}min\left[ \frac{a}{b}-\frac{1}{b}P_{1}, K \right] \quad se \quad P_{2}=P_{1}\leq a \\ min\left[ \frac{a}{b}-\frac{1}{b}P_{1}, K \right] \quad se \quad P_{2}&gt;P_{1}\leq a \\ 0 \quad caso \quad contrário \end{cases}
\]</span></p>
<p>O lucro da empresa <span class="math inline">\(i\)</span> é definido de forma similar, de acordo com a Função Melhor Resposta:</p>
<p><span class="math display">\[
\pi_{i}=\begin{cases} (p_{i}-c) min \left[ \frac{a}{b}-K-\frac{1}{b}P_{1}, K \right] \quad se \quad P_{2}&lt;P_{1} \leq a-bK \\ (p_{i}-c)\frac{1}{2}min\left[ \frac{a}{b}-\frac{1}{b}P_{1}, K \right] \quad se \quad P_{2}=P_{1}\leq a \\ (p_{i}-c)min\left[ \frac{a}{b}-\frac{1}{b}P_{1}, K \right] \quad se \quad P_{2}&gt;P_{1}\leq a \\ 0 \quad caso \quad contrário \end{cases}
\]</span>
Neste caso a construção da função melhor resposta por meio do “deriva e iguala a zero” é extremamente complicada, pois a função lucro tem um monte de descontinuidades. Iremos então começar buscando estratégias dominadas, para aí determinarmos quais seriam as melhores respostas.</p>
<p>Duas estratégias são dominadas para a empresa 1: <span class="math inline">\(p_{1}&gt;a\)</span> e <span class="math inline">\(p_{1}&lt;c\)</span>. No primeiro dos casos, a empresa não venderia nada, e no segundo dos casos o lucro seria negativo para qualquer venda. Ou seja, a FMR deve se limitar a <span class="math inline">\(c\leq P_{1}&lt; a\)</span>.</p>
<p>Para <span class="math inline">\(P_{1}\leq a-2bK\)</span>, e a empresa 2 cobrando um preço menor, a empresa 1 necessariamente vende <span class="math inline">\(K\)</span> (obtido a partir de se igualar os dois argumentos do “min” da primeira linha da função lucro). Só que se você vai vender exatamente <span class="math inline">\(K\)</span>, a melhor coisa a fazer para maximizar os lucros é cobrar <span class="math inline">\(a-2bK\)</span>. Ou seja, para qualquer <span class="math inline">\(P_{2}&lt;a-2bK\)</span>, a melhor resposta da firma 1 é cobrar <span class="math inline">\(a-2bK\)</span>.</p>
<p>Caso a empresa 2 cobre um preço superior a <span class="math inline">\(a-2bK\)</span>, a melhor resposta fica um pouco mais complexa. Caso a empresa 2 cobre um preço abaixo de <span class="math inline">\(a-bK\)</span> (obtido a partir de se igualar os dois argumentos do “min” da segunda linha da função lucro), a melhor resposta da empresa 1 é cobrar <span class="math inline">\(P_{2}-\varepsilon\)</span>, pois toma todo o mercado, vende <span class="math inline">\(K\)</span>. Caso a firma 2 cobre um preço maior do que <span class="math inline">\(a-bK\)</span>, a firma 1 vai cobrar <span class="math inline">\(a-bK\)</span> - pois se ela cobrar mais, ela passa a vender menos do que a capacidade dela.</p>
<p>A função melhor resposta fica sendo então:</p>
<table>
<thead>
<tr class="header">
<th></th>
<th>Melhor Resposta Firma 1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(P_{2}\in[c,a-2bk]\)</span></td>
<td><span class="math inline">\(a-2bK\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(P_{2}\in]a-2bK,a-bk[\)</span></td>
<td><span class="math inline">\(P_{2}-\varepsilon\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(P_{2}\in[a-bK,\infty[\)</span></td>
<td><span class="math inline">\(a-bK\)</span></td>
</tr>
</tbody>
</table>
<p>A firma 2 tem uma tabela bastante similar, o que implica que este jogo tem apenas um perfil de estratégias puras que é Equilíbrio de Nash, <span class="math inline">\(P_{1}=P_{2}=a-2bK\)</span>. As funções Melhor Resposta neste caso ficam sendo:</p>
<div class="figure">
<img src="Bertrand.png" alt="" />
<p class="caption">Funções Melhor Resposta</p>
</div>
<p>Neste caso, temos um equilíbrio em estratégias puras, com preços acima dos custos marginais. Só que este resultado depende de algumas premissas:</p>
<ul>
<li>Capacidade <em>não muito grande</em>. Quanto maior <span class="math inline">\(K\)</span>, mais próxima da origem o equilíbrio está.</li>
<li>Os consumidores são racionados aleatoriamente. Ou seja, a função demanda residual é similar à demanda original.</li>
</ul>
<p>Caso alguma dessas premissas não valha, o resultado de equilíbrio em estratégias puras com preços iguais e acima dos custos marginais não necessariamente se mantém.</p>
</div>
</div>
<div id="modelos-sequenciais-stackelberg" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Modelos Sequenciais: Stackelberg</h2>
<p>No modelo de Cournot que vimos anteriormente, consideramos o jogo simultâneo, ou seja, não havia possibilidade de um dos jogadores agir de forma condicional ao que o outro fizesse. Em muitos casos isso não é verdade. Vamos supor, ainda usando a estrutura do modelo de Cournot da aula passada, que uma das empresas é capaz de agir de forma condicional ao que o seu oponente fizesse. Este modelo foi desenvolvido em 1934 por Heinrich von Stackelberg e por isso é chamado, não surpreendentemente, de ``Modelo de Stackelberg’’, ou modelo da firma líder e firma seguidora.</p>
<div id="apresentação-do-modelo" class="section level3" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Apresentação do modelo</h3>
<p>Vamos supor que existam duas firmas em um mercado, representadas por <span class="math inline">\(i=1,2\)</span>. No entanto, neste mercado a primeira das companhias também tem precedência na escolha da quantidade produzida em relação à segunda. Ou, em outras palavras, a segunda empresa pode reagir ao que a primeira fizer. Este fato pode ser devido a um monte de motivos, seja por uma tecnologia mais avançada ou admiistração mais eficiente.</p>
<p>Como são as estratégias destas empresas? A da firma 1 – que vou chamar de líder – é bastante simples, a determinação de um valor para a quantidade produzida.
Já para a firma 2 a definição de estratégias é mais complexa, pois especifica uma ação para a firma 2 para cada quantidade produzida pela firma 1.</p>
<p>Veremos como isto é operacionalizado usando a mesma premissa de demanda linear e custos marginais constantes que vimos anteriormente, ou:</p>
<p><span class="math display">\[
P=a-b(q_{1}+q_{2})
\]</span></p>
<p>Vamos assumir também que os custos marginais são constantes e iguais, o que significa que <span class="math inline">\(CT_{i}=c\times q_{i}, i=1,2\)</span>. Isso leva às seguintes funções lucro para cada uma das firmas.</p>
<p><span class="math display">\[
\begin{aligned}
\pi_{i}&amp;=(P-c_{i})q_{i}=(a-b(q_{1}+q_{2})-c)q_{i}\\
\pi_{1}&amp;=(P-c_{1})q_{1}=(a-b(q_{1}+q_{2})-c)q_{1}\\
\pi_{2}&amp;=(P-c_{2})q_{2}=(a-b(q_{1}+q_{2})-c)q_{2}
\end{aligned}
\]</span></p>
<p>Aí aqui começa a aparecer a diferença entre este modelo. Uma vez que o jogo é sequencial, temos que resolver este jogo por indução retrospectiva. Para a firma 2, a seguidora que se move depois, temos uma função melhor resposta tradicional – ela toma como dada a quantidade produzida pela empresa 1 e escolhe qual a quantidade que, para ela, maximiza seus lucros.</p>
<p><span class="math display">\[
\begin{aligned}
\frac{\partial \pi_{2}}{\partial q_{2}}&amp;=a-2bq_{2}-bq_{1}-cq_{2}\\
q_{2}&amp;=\frac{a-bq_{1}-c}{2b}
\end{aligned}
\]</span></p>
<p>Esta função melhor resposta da firma 2 será utilizada para derivarmos o equilíbrio na primeira etapa. Como? Por meio da substituição desta função melhor resposta na função lucro da firma 1. Ou seja, temos:</p>
<p><span class="math display">\[
\begin{aligned}
\pi_{1}&amp;=\left(a-b\left( \frac{2bq_{1}+a -bq_{1}-c}{2b} \right)  \right)q_{q}-cq_{1}\\
\pi_{1}&amp;=\left(a-\frac{1}{2}\left(a + bq_{1}-c \right)  \right)q_{q}-cq_{1}
\end{aligned}
\]</span></p>
<p>Derivando esta função lucro em termos da estratégia a ser escolhida pela empresa 1, temos então:</p>
<p><span class="math display">\[
\begin{aligned}
\frac{\partial \pi_{1}}{\partial q_{1}} &amp;= \frac{a-c}{2}-bq_{1}=0\\
q_{1}&amp;=\frac{a-c}{2b}
\end{aligned}
\]</span></p>
<p>Podemos agora obter a quantidade produzida pela empresa 2, simplesmente substituindo o último dos resultados na função melhor resposta mais acima.</p>
<p><span class="math display">\[
\begin{aligned}
q_{2}&amp;=\frac{a-c-b\left(\frac{a-c}{2b} \right)}{2b}\\
q_{2}&amp;=\frac{a-c}{4b}
\end{aligned}
\]</span></p>
<p>Podemos notar que este modelo implica que a empresa que pode reagir acaba tendo menor produção e menores lucros que a empresa que não reage. Este é um tipo de situação em que não há vantagem em se ter flexibilidade; muito pelo contrário, há vantagens para o comprometimento.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-porter1983study" class="csl-entry">
Porter, Robert H. 1983. <span>“A Study of Cartel Stability: The Joint Executive Committee, 1880-1886.”</span> <em>The Bell Journal of Economics</em>, 301–14.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="competição-perfeita-e-monopólio.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modelo-de-mankiw-e-whinston.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jules32/bookdown-tutorial/edit/master/04-Oligopolio.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["livro.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
